/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables;


import com.ivo.school.Keys;
import com.ivo.school.Mydb;
import com.ivo.school.tables.records.AssignmentsCoursesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentsCourses extends TableImpl<AssignmentsCoursesRecord> {

    private static final long serialVersionUID = -1474420109;

    /**
     * The reference instance of <code>mydb.assignments_courses</code>
     */
    public static final AssignmentsCourses ASSIGNMENTS_COURSES = new AssignmentsCourses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssignmentsCoursesRecord> getRecordType() {
        return AssignmentsCoursesRecord.class;
    }

    /**
     * The column <code>mydb.assignments_courses.id</code>.
     */
    public final TableField<AssignmentsCoursesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.assignments_courses.assignment_id</code>.
     */
    public final TableField<AssignmentsCoursesRecord, Integer> ASSIGNMENT_ID = createField("assignment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.assignments_courses.course_id</code>.
     */
    public final TableField<AssignmentsCoursesRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.assignments_courses.createdAt</code>.
     */
    public final TableField<AssignmentsCoursesRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mydb.assignments_courses.updatedAt</code>.
     */
    public final TableField<AssignmentsCoursesRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mydb.assignments_courses</code> table reference
     */
    public AssignmentsCourses() {
        this("assignments_courses", null);
    }

    /**
     * Create an aliased <code>mydb.assignments_courses</code> table reference
     */
    public AssignmentsCourses(String alias) {
        this(alias, ASSIGNMENTS_COURSES);
    }

    private AssignmentsCourses(String alias, Table<AssignmentsCoursesRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssignmentsCourses(String alias, Table<AssignmentsCoursesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AssignmentsCoursesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ASSIGNMENTS_COURSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AssignmentsCoursesRecord> getPrimaryKey() {
        return Keys.KEY_ASSIGNMENTS_COURSES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AssignmentsCoursesRecord>> getKeys() {
        return Arrays.<UniqueKey<AssignmentsCoursesRecord>>asList(Keys.KEY_ASSIGNMENTS_COURSES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AssignmentsCoursesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AssignmentsCoursesRecord, ?>>asList(Keys.FK_ASSIGNMENTS_COURSES_ASIGNMENT, Keys.FK_ASSIGNMENTS_COURSES_COURSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsCourses as(String alias) {
        return new AssignmentsCourses(alias, this);
    }

    /**
     * Rename this table
     */
    public AssignmentsCourses rename(String name) {
        return new AssignmentsCourses(name, null);
    }
}
