/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables;


import com.ivo.school.Keys;
import com.ivo.school.Mydb;
import com.ivo.school.tables.records.CourseNewsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseNews extends TableImpl<CourseNewsRecord> {

    private static final long serialVersionUID = -130673372;

    /**
     * The reference instance of <code>mydb.course_news</code>
     */
    public static final CourseNews COURSE_NEWS = new CourseNews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourseNewsRecord> getRecordType() {
        return CourseNewsRecord.class;
    }

    /**
     * The column <code>mydb.course_news.id</code>.
     */
    public final TableField<CourseNewsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.course_news.course_id</code>.
     */
    public final TableField<CourseNewsRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.course_news.news_id</code>.
     */
    public final TableField<CourseNewsRecord, Integer> NEWS_ID = createField("news_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.course_news.createdAt</code>.
     */
    public final TableField<CourseNewsRecord, Date> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>mydb.course_news.updatedAt</code>.
     */
    public final TableField<CourseNewsRecord, Date> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>mydb.course_news</code> table reference
     */
    public CourseNews() {
        this("course_news", null);
    }

    /**
     * Create an aliased <code>mydb.course_news</code> table reference
     */
    public CourseNews(String alias) {
        this(alias, COURSE_NEWS);
    }

    private CourseNews(String alias, Table<CourseNewsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CourseNews(String alias, Table<CourseNewsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CourseNewsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COURSE_NEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CourseNewsRecord> getPrimaryKey() {
        return Keys.KEY_COURSE_NEWS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CourseNewsRecord>> getKeys() {
        return Arrays.<UniqueKey<CourseNewsRecord>>asList(Keys.KEY_COURSE_NEWS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CourseNewsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CourseNewsRecord, ?>>asList(Keys.FK_COURSE_NEWS_COURSE, Keys.FK_COURSE_NEWS_NEWS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNews as(String alias) {
        return new CourseNews(alias, this);
    }

    /**
     * Rename this table
     */
    public CourseNews rename(String name) {
        return new CourseNews(name, null);
    }
}
