/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables;


import com.ivo.school.Keys;
import com.ivo.school.Mydb;
import com.ivo.school.tables.records.ExamsCoursesRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamsCourses extends TableImpl<ExamsCoursesRecord> {

    private static final long serialVersionUID = 530429159;

    /**
     * The reference instance of <code>mydb.exams_courses</code>
     */
    public static final ExamsCourses EXAMS_COURSES = new ExamsCourses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExamsCoursesRecord> getRecordType() {
        return ExamsCoursesRecord.class;
    }

    /**
     * The column <code>mydb.exams_courses.id</code>.
     */
    public final TableField<ExamsCoursesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.exams_courses.exam_id</code>.
     */
    public final TableField<ExamsCoursesRecord, Integer> EXAM_ID = createField("exam_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.exams_courses.course_id</code>.
     */
    public final TableField<ExamsCoursesRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.exams_courses.createdAt</code>.
     */
    public final TableField<ExamsCoursesRecord, Date> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>mydb.exams_courses.updatedAt</code>.
     */
    public final TableField<ExamsCoursesRecord, Date> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>mydb.exams_courses</code> table reference
     */
    public ExamsCourses() {
        this("exams_courses", null);
    }

    /**
     * Create an aliased <code>mydb.exams_courses</code> table reference
     */
    public ExamsCourses(String alias) {
        this(alias, EXAMS_COURSES);
    }

    private ExamsCourses(String alias, Table<ExamsCoursesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExamsCourses(String alias, Table<ExamsCoursesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExamsCoursesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EXAMS_COURSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExamsCoursesRecord> getPrimaryKey() {
        return Keys.KEY_EXAMS_COURSES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExamsCoursesRecord>> getKeys() {
        return Arrays.<UniqueKey<ExamsCoursesRecord>>asList(Keys.KEY_EXAMS_COURSES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExamsCoursesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExamsCoursesRecord, ?>>asList(Keys.FK_EXAMS_COURSES_EXAMS, Keys.FK_EXAMS_COURSES_COURSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsCourses as(String alias) {
        return new ExamsCourses(alias, this);
    }

    /**
     * Rename this table
     */
    public ExamsCourses rename(String name) {
        return new ExamsCourses(name, null);
    }
}
