/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables;


import com.ivo.school.Keys;
import com.ivo.school.Mydb;
import com.ivo.school.tables.records.StudentsCoursesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsCourses extends TableImpl<StudentsCoursesRecord> {

    private static final long serialVersionUID = -2086889964;

    /**
     * The reference instance of <code>mydb.students_courses</code>
     */
    public static final StudentsCourses STUDENTS_COURSES = new StudentsCourses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentsCoursesRecord> getRecordType() {
        return StudentsCoursesRecord.class;
    }

    /**
     * The column <code>mydb.students_courses.id</code>.
     */
    public final TableField<StudentsCoursesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.students_courses.student_id</code>.
     */
    public final TableField<StudentsCoursesRecord, Integer> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.students_courses.course_id</code>.
     */
    public final TableField<StudentsCoursesRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mydb.students_courses.remarks</code>.
     */
    public final TableField<StudentsCoursesRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>mydb.students_courses.createdAt</code>.
     */
    public final TableField<StudentsCoursesRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mydb.students_courses.updatedAt</code>.
     */
    public final TableField<StudentsCoursesRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mydb.students_courses</code> table reference
     */
    public StudentsCourses() {
        this("students_courses", null);
    }

    /**
     * Create an aliased <code>mydb.students_courses</code> table reference
     */
    public StudentsCourses(String alias) {
        this(alias, STUDENTS_COURSES);
    }

    private StudentsCourses(String alias, Table<StudentsCoursesRecord> aliased) {
        this(alias, aliased, null);
    }

    private StudentsCourses(String alias, Table<StudentsCoursesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StudentsCoursesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STUDENTS_COURSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudentsCoursesRecord> getPrimaryKey() {
        return Keys.KEY_STUDENTS_COURSES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudentsCoursesRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentsCoursesRecord>>asList(Keys.KEY_STUDENTS_COURSES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StudentsCoursesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StudentsCoursesRecord, ?>>asList(Keys.FK_STUDENT_HAS_COURSE_STUDENT1, Keys.FK_STUDENT_HAS_COURSE_COURSE1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCourses as(String alias) {
        return new StudentsCourses(alias, this);
    }

    /**
     * Rename this table
     */
    public StudentsCourses rename(String name) {
        return new StudentsCourses(name, null);
    }
}
