/**
 * This class is generated by jOOQ
 */
package com.ivo.school;


import com.ivo.school.tables.Assignments;
import com.ivo.school.tables.AssignmentsCourses;
import com.ivo.school.tables.Attendances;
import com.ivo.school.tables.ClassNews;
import com.ivo.school.tables.Classes;
import com.ivo.school.tables.CourseNews;
import com.ivo.school.tables.CourseNotes;
import com.ivo.school.tables.Courses;
import com.ivo.school.tables.Exams;
import com.ivo.school.tables.ExamsCourses;
import com.ivo.school.tables.Grades;
import com.ivo.school.tables.Holidays;
import com.ivo.school.tables.Lecturers;
import com.ivo.school.tables.LecturersCourses;
import com.ivo.school.tables.News;
import com.ivo.school.tables.Notes;
import com.ivo.school.tables.Parents;
import com.ivo.school.tables.ParentsStudents;
import com.ivo.school.tables.PeriodNotes;
import com.ivo.school.tables.Periods;
import com.ivo.school.tables.SchoolData;
import com.ivo.school.tables.Students;
import com.ivo.school.tables.StudentsCourses;
import com.ivo.school.tables.StudentsCoursesAssignments;
import com.ivo.school.tables.StudentsCoursesExams;
import com.ivo.school.tables.Subjects;
import com.ivo.school.tables.records.AssignmentsCoursesRecord;
import com.ivo.school.tables.records.AssignmentsRecord;
import com.ivo.school.tables.records.AttendancesRecord;
import com.ivo.school.tables.records.ClassNewsRecord;
import com.ivo.school.tables.records.ClassesRecord;
import com.ivo.school.tables.records.CourseNewsRecord;
import com.ivo.school.tables.records.CourseNotesRecord;
import com.ivo.school.tables.records.CoursesRecord;
import com.ivo.school.tables.records.ExamsCoursesRecord;
import com.ivo.school.tables.records.ExamsRecord;
import com.ivo.school.tables.records.GradesRecord;
import com.ivo.school.tables.records.HolidaysRecord;
import com.ivo.school.tables.records.LecturersCoursesRecord;
import com.ivo.school.tables.records.LecturersRecord;
import com.ivo.school.tables.records.NewsRecord;
import com.ivo.school.tables.records.NotesRecord;
import com.ivo.school.tables.records.ParentsRecord;
import com.ivo.school.tables.records.ParentsStudentsRecord;
import com.ivo.school.tables.records.PeriodNotesRecord;
import com.ivo.school.tables.records.PeriodsRecord;
import com.ivo.school.tables.records.SchoolDataRecord;
import com.ivo.school.tables.records.StudentsCoursesAssignmentsRecord;
import com.ivo.school.tables.records.StudentsCoursesExamsRecord;
import com.ivo.school.tables.records.StudentsCoursesRecord;
import com.ivo.school.tables.records.StudentsRecord;
import com.ivo.school.tables.records.SubjectsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>mydb</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AssignmentsRecord, Integer> IDENTITY_ASSIGNMENTS = Identities0.IDENTITY_ASSIGNMENTS;
    public static final Identity<AssignmentsCoursesRecord, Integer> IDENTITY_ASSIGNMENTS_COURSES = Identities0.IDENTITY_ASSIGNMENTS_COURSES;
    public static final Identity<AttendancesRecord, Integer> IDENTITY_ATTENDANCES = Identities0.IDENTITY_ATTENDANCES;
    public static final Identity<ClassesRecord, Integer> IDENTITY_CLASSES = Identities0.IDENTITY_CLASSES;
    public static final Identity<ClassNewsRecord, Integer> IDENTITY_CLASS_NEWS = Identities0.IDENTITY_CLASS_NEWS;
    public static final Identity<CoursesRecord, Integer> IDENTITY_COURSES = Identities0.IDENTITY_COURSES;
    public static final Identity<CourseNewsRecord, Integer> IDENTITY_COURSE_NEWS = Identities0.IDENTITY_COURSE_NEWS;
    public static final Identity<CourseNotesRecord, Integer> IDENTITY_COURSE_NOTES = Identities0.IDENTITY_COURSE_NOTES;
    public static final Identity<ExamsRecord, Integer> IDENTITY_EXAMS = Identities0.IDENTITY_EXAMS;
    public static final Identity<ExamsCoursesRecord, Integer> IDENTITY_EXAMS_COURSES = Identities0.IDENTITY_EXAMS_COURSES;
    public static final Identity<GradesRecord, Integer> IDENTITY_GRADES = Identities0.IDENTITY_GRADES;
    public static final Identity<HolidaysRecord, Integer> IDENTITY_HOLIDAYS = Identities0.IDENTITY_HOLIDAYS;
    public static final Identity<LecturersRecord, Integer> IDENTITY_LECTURERS = Identities0.IDENTITY_LECTURERS;
    public static final Identity<NewsRecord, Integer> IDENTITY_NEWS = Identities0.IDENTITY_NEWS;
    public static final Identity<NotesRecord, Integer> IDENTITY_NOTES = Identities0.IDENTITY_NOTES;
    public static final Identity<ParentsRecord, Integer> IDENTITY_PARENTS = Identities0.IDENTITY_PARENTS;
    public static final Identity<ParentsStudentsRecord, Integer> IDENTITY_PARENTS_STUDENTS = Identities0.IDENTITY_PARENTS_STUDENTS;
    public static final Identity<PeriodsRecord, Integer> IDENTITY_PERIODS = Identities0.IDENTITY_PERIODS;
    public static final Identity<PeriodNotesRecord, Integer> IDENTITY_PERIOD_NOTES = Identities0.IDENTITY_PERIOD_NOTES;
    public static final Identity<SchoolDataRecord, Integer> IDENTITY_SCHOOL_DATA = Identities0.IDENTITY_SCHOOL_DATA;
    public static final Identity<StudentsRecord, Integer> IDENTITY_STUDENTS = Identities0.IDENTITY_STUDENTS;
    public static final Identity<StudentsCoursesRecord, Integer> IDENTITY_STUDENTS_COURSES = Identities0.IDENTITY_STUDENTS_COURSES;
    public static final Identity<StudentsCoursesAssignmentsRecord, Integer> IDENTITY_STUDENTS_COURSES_ASSIGNMENTS = Identities0.IDENTITY_STUDENTS_COURSES_ASSIGNMENTS;
    public static final Identity<StudentsCoursesExamsRecord, Integer> IDENTITY_STUDENTS_COURSES_EXAMS = Identities0.IDENTITY_STUDENTS_COURSES_EXAMS;
    public static final Identity<SubjectsRecord, Integer> IDENTITY_SUBJECTS = Identities0.IDENTITY_SUBJECTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssignmentsRecord> KEY_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<AssignmentsCoursesRecord> KEY_ASSIGNMENTS_COURSES_PRIMARY = UniqueKeys0.KEY_ASSIGNMENTS_COURSES_PRIMARY;
    public static final UniqueKey<AttendancesRecord> KEY_ATTENDANCES_PRIMARY = UniqueKeys0.KEY_ATTENDANCES_PRIMARY;
    public static final UniqueKey<ClassesRecord> KEY_CLASSES_PRIMARY = UniqueKeys0.KEY_CLASSES_PRIMARY;
    public static final UniqueKey<ClassNewsRecord> KEY_CLASS_NEWS_PRIMARY = UniqueKeys0.KEY_CLASS_NEWS_PRIMARY;
    public static final UniqueKey<CoursesRecord> KEY_COURSES_PRIMARY = UniqueKeys0.KEY_COURSES_PRIMARY;
    public static final UniqueKey<CourseNewsRecord> KEY_COURSE_NEWS_PRIMARY = UniqueKeys0.KEY_COURSE_NEWS_PRIMARY;
    public static final UniqueKey<CourseNotesRecord> KEY_COURSE_NOTES_PRIMARY = UniqueKeys0.KEY_COURSE_NOTES_PRIMARY;
    public static final UniqueKey<ExamsRecord> KEY_EXAMS_PRIMARY = UniqueKeys0.KEY_EXAMS_PRIMARY;
    public static final UniqueKey<ExamsCoursesRecord> KEY_EXAMS_COURSES_PRIMARY = UniqueKeys0.KEY_EXAMS_COURSES_PRIMARY;
    public static final UniqueKey<GradesRecord> KEY_GRADES_PRIMARY = UniqueKeys0.KEY_GRADES_PRIMARY;
    public static final UniqueKey<HolidaysRecord> KEY_HOLIDAYS_PRIMARY = UniqueKeys0.KEY_HOLIDAYS_PRIMARY;
    public static final UniqueKey<LecturersRecord> KEY_LECTURERS_PRIMARY = UniqueKeys0.KEY_LECTURERS_PRIMARY;
    public static final UniqueKey<LecturersRecord> KEY_LECTURERS_REGNUMBER_UNIQUE = UniqueKeys0.KEY_LECTURERS_REGNUMBER_UNIQUE;
    public static final UniqueKey<LecturersCoursesRecord> KEY_LECTURERS_COURSES_PRIMARY = UniqueKeys0.KEY_LECTURERS_COURSES_PRIMARY;
    public static final UniqueKey<NewsRecord> KEY_NEWS_PRIMARY = UniqueKeys0.KEY_NEWS_PRIMARY;
    public static final UniqueKey<NotesRecord> KEY_NOTES_PRIMARY = UniqueKeys0.KEY_NOTES_PRIMARY;
    public static final UniqueKey<ParentsRecord> KEY_PARENTS_PRIMARY = UniqueKeys0.KEY_PARENTS_PRIMARY;
    public static final UniqueKey<ParentsRecord> KEY_PARENTS_EMAIL = UniqueKeys0.KEY_PARENTS_EMAIL;
    public static final UniqueKey<ParentsRecord> KEY_PARENTS_REGNUMBER_UNIQUE = UniqueKeys0.KEY_PARENTS_REGNUMBER_UNIQUE;
    public static final UniqueKey<ParentsStudentsRecord> KEY_PARENTS_STUDENTS_PRIMARY = UniqueKeys0.KEY_PARENTS_STUDENTS_PRIMARY;
    public static final UniqueKey<PeriodsRecord> KEY_PERIODS_PRIMARY = UniqueKeys0.KEY_PERIODS_PRIMARY;
    public static final UniqueKey<PeriodNotesRecord> KEY_PERIOD_NOTES_PRIMARY = UniqueKeys0.KEY_PERIOD_NOTES_PRIMARY;
    public static final UniqueKey<SchoolDataRecord> KEY_SCHOOL_DATA_PRIMARY = UniqueKeys0.KEY_SCHOOL_DATA_PRIMARY;
    public static final UniqueKey<StudentsRecord> KEY_STUDENTS_PRIMARY = UniqueKeys0.KEY_STUDENTS_PRIMARY;
    public static final UniqueKey<StudentsRecord> KEY_STUDENTS_REGNUMBER_UNIQUE = UniqueKeys0.KEY_STUDENTS_REGNUMBER_UNIQUE;
    public static final UniqueKey<StudentsCoursesRecord> KEY_STUDENTS_COURSES_PRIMARY = UniqueKeys0.KEY_STUDENTS_COURSES_PRIMARY;
    public static final UniqueKey<StudentsCoursesAssignmentsRecord> KEY_STUDENTS_COURSES_ASSIGNMENTS_PRIMARY = UniqueKeys0.KEY_STUDENTS_COURSES_ASSIGNMENTS_PRIMARY;
    public static final UniqueKey<StudentsCoursesExamsRecord> KEY_STUDENTS_COURSES_EXAMS_PRIMARY = UniqueKeys0.KEY_STUDENTS_COURSES_EXAMS_PRIMARY;
    public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_PRIMARY = UniqueKeys0.KEY_SUBJECTS_PRIMARY;
    public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_NAME = UniqueKeys0.KEY_SUBJECTS_NAME;
    public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_SHORT_NAME = UniqueKeys0.KEY_SUBJECTS_SHORT_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssignmentsRecord, LecturersRecord> FK_ASSIGNMENT_LECTURER1 = ForeignKeys0.FK_ASSIGNMENT_LECTURER1;
    public static final ForeignKey<AssignmentsCoursesRecord, AssignmentsRecord> FK_ASSIGNMENTS_COURSES_ASIGNMENT = ForeignKeys0.FK_ASSIGNMENTS_COURSES_ASIGNMENT;
    public static final ForeignKey<AssignmentsCoursesRecord, CoursesRecord> FK_ASSIGNMENTS_COURSES_COURSE = ForeignKeys0.FK_ASSIGNMENTS_COURSES_COURSE;
    public static final ForeignKey<AttendancesRecord, StudentsRecord> FK_ATTENDANCE_STUDENTS = ForeignKeys0.FK_ATTENDANCE_STUDENTS;
    public static final ForeignKey<AttendancesRecord, PeriodsRecord> FK_ATTENDANCE_PERIODS = ForeignKeys0.FK_ATTENDANCE_PERIODS;
    public static final ForeignKey<ClassesRecord, LecturersRecord> FK_CLASS_LECTURER1 = ForeignKeys0.FK_CLASS_LECTURER1;
    public static final ForeignKey<ClassesRecord, LecturersRecord> LECTURER_ID = ForeignKeys0.LECTURER_ID;
    public static final ForeignKey<CoursesRecord, ClassesRecord> FK_CLASS_HAS_SUBJECT_CLASS2 = ForeignKeys0.FK_CLASS_HAS_SUBJECT_CLASS2;
    public static final ForeignKey<CoursesRecord, SubjectsRecord> FK_CLASS_HAS_SUBJECT_SUBJECT2 = ForeignKeys0.FK_CLASS_HAS_SUBJECT_SUBJECT2;
    public static final ForeignKey<CourseNewsRecord, CoursesRecord> FK_COURSE_NEWS_COURSE = ForeignKeys0.FK_COURSE_NEWS_COURSE;
    public static final ForeignKey<CourseNewsRecord, NewsRecord> FK_COURSE_NEWS_NEWS = ForeignKeys0.FK_COURSE_NEWS_NEWS;
    public static final ForeignKey<CourseNotesRecord, NotesRecord> FK_COURSE_NOTES_NOTES = ForeignKeys0.FK_COURSE_NOTES_NOTES;
    public static final ForeignKey<CourseNotesRecord, CoursesRecord> FK_COURSE_NOTES_COURSES = ForeignKeys0.FK_COURSE_NOTES_COURSES;
    public static final ForeignKey<ExamsCoursesRecord, ExamsRecord> FK_EXAMS_COURSES_EXAMS = ForeignKeys0.FK_EXAMS_COURSES_EXAMS;
    public static final ForeignKey<ExamsCoursesRecord, CoursesRecord> FK_EXAMS_COURSES_COURSE = ForeignKeys0.FK_EXAMS_COURSES_COURSE;
    public static final ForeignKey<LecturersCoursesRecord, LecturersRecord> FK_LECTURER_HAS_COURSE_LECTURER1 = ForeignKeys0.FK_LECTURER_HAS_COURSE_LECTURER1;
    public static final ForeignKey<LecturersCoursesRecord, CoursesRecord> FK_LECTURER_HAS_COURSE_COURSE1 = ForeignKeys0.FK_LECTURER_HAS_COURSE_COURSE1;
    public static final ForeignKey<NewsRecord, LecturersRecord> FK_NEWS_LECTURER1 = ForeignKeys0.FK_NEWS_LECTURER1;
    public static final ForeignKey<NotesRecord, LecturersRecord> FK_NOTES_LECTURERS = ForeignKeys0.FK_NOTES_LECTURERS;
    public static final ForeignKey<ParentsStudentsRecord, ParentsRecord> FK_PARENT_HAS_STUDENT_PARENT = ForeignKeys0.FK_PARENT_HAS_STUDENT_PARENT;
    public static final ForeignKey<ParentsStudentsRecord, StudentsRecord> FK_PARENT_HAS_STUDENT_STUDENT1 = ForeignKeys0.FK_PARENT_HAS_STUDENT_STUDENT1;
    public static final ForeignKey<PeriodsRecord, CoursesRecord> FK_PERIOD_COURSE1 = ForeignKeys0.FK_PERIOD_COURSE1;
    public static final ForeignKey<PeriodNotesRecord, NotesRecord> FK_PERIOD_NOTES_NOTES = ForeignKeys0.FK_PERIOD_NOTES_NOTES;
    public static final ForeignKey<PeriodNotesRecord, PeriodsRecord> FK_PERIOD_NOTES_PERIODS = ForeignKeys0.FK_PERIOD_NOTES_PERIODS;
    public static final ForeignKey<StudentsRecord, ClassesRecord> FK_STUDENTS_CLASSES = ForeignKeys0.FK_STUDENTS_CLASSES;
    public static final ForeignKey<StudentsCoursesRecord, StudentsRecord> FK_STUDENT_HAS_COURSE_STUDENT1 = ForeignKeys0.FK_STUDENT_HAS_COURSE_STUDENT1;
    public static final ForeignKey<StudentsCoursesRecord, CoursesRecord> FK_STUDENT_HAS_COURSE_COURSE1 = ForeignKeys0.FK_STUDENT_HAS_COURSE_COURSE1;
    public static final ForeignKey<StudentsCoursesAssignmentsRecord, StudentsRecord> FK_STUDENT_COURSES_ASSIGNMENT_STUDENT = ForeignKeys0.FK_STUDENT_COURSES_ASSIGNMENT_STUDENT;
    public static final ForeignKey<StudentsCoursesAssignmentsRecord, CoursesRecord> FK_STUDENT_COURSES_ASSIGNMENT_COURSE = ForeignKeys0.FK_STUDENT_COURSES_ASSIGNMENT_COURSE;
    public static final ForeignKey<StudentsCoursesAssignmentsRecord, AssignmentsRecord> FK_STUDENT_COURSES_ASSIGNMENT_ASSIGNMENT1 = ForeignKeys0.FK_STUDENT_COURSES_ASSIGNMENT_ASSIGNMENT1;
    public static final ForeignKey<StudentsCoursesExamsRecord, StudentsRecord> FK_STUDENT = ForeignKeys0.FK_STUDENT;
    public static final ForeignKey<StudentsCoursesExamsRecord, CoursesRecord> FK_COURSE = ForeignKeys0.FK_COURSE;
    public static final ForeignKey<StudentsCoursesExamsRecord, ExamsRecord> FK_EXAM = ForeignKeys0.FK_EXAM;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AssignmentsRecord, Integer> IDENTITY_ASSIGNMENTS = createIdentity(Assignments.ASSIGNMENTS, Assignments.ASSIGNMENTS.ID);
        public static Identity<AssignmentsCoursesRecord, Integer> IDENTITY_ASSIGNMENTS_COURSES = createIdentity(AssignmentsCourses.ASSIGNMENTS_COURSES, AssignmentsCourses.ASSIGNMENTS_COURSES.ID);
        public static Identity<AttendancesRecord, Integer> IDENTITY_ATTENDANCES = createIdentity(Attendances.ATTENDANCES, Attendances.ATTENDANCES.ID);
        public static Identity<ClassesRecord, Integer> IDENTITY_CLASSES = createIdentity(Classes.CLASSES, Classes.CLASSES.ID);
        public static Identity<ClassNewsRecord, Integer> IDENTITY_CLASS_NEWS = createIdentity(ClassNews.CLASS_NEWS, ClassNews.CLASS_NEWS.ID);
        public static Identity<CoursesRecord, Integer> IDENTITY_COURSES = createIdentity(Courses.COURSES, Courses.COURSES.ID);
        public static Identity<CourseNewsRecord, Integer> IDENTITY_COURSE_NEWS = createIdentity(CourseNews.COURSE_NEWS, CourseNews.COURSE_NEWS.ID);
        public static Identity<CourseNotesRecord, Integer> IDENTITY_COURSE_NOTES = createIdentity(CourseNotes.COURSE_NOTES, CourseNotes.COURSE_NOTES.ID);
        public static Identity<ExamsRecord, Integer> IDENTITY_EXAMS = createIdentity(Exams.EXAMS, Exams.EXAMS.ID);
        public static Identity<ExamsCoursesRecord, Integer> IDENTITY_EXAMS_COURSES = createIdentity(ExamsCourses.EXAMS_COURSES, ExamsCourses.EXAMS_COURSES.ID);
        public static Identity<GradesRecord, Integer> IDENTITY_GRADES = createIdentity(Grades.GRADES, Grades.GRADES.ID);
        public static Identity<HolidaysRecord, Integer> IDENTITY_HOLIDAYS = createIdentity(Holidays.HOLIDAYS, Holidays.HOLIDAYS.ID);
        public static Identity<LecturersRecord, Integer> IDENTITY_LECTURERS = createIdentity(Lecturers.LECTURERS, Lecturers.LECTURERS.ID);
        public static Identity<NewsRecord, Integer> IDENTITY_NEWS = createIdentity(News.NEWS, News.NEWS.ID);
        public static Identity<NotesRecord, Integer> IDENTITY_NOTES = createIdentity(Notes.NOTES, Notes.NOTES.ID);
        public static Identity<ParentsRecord, Integer> IDENTITY_PARENTS = createIdentity(Parents.PARENTS, Parents.PARENTS.ID);
        public static Identity<ParentsStudentsRecord, Integer> IDENTITY_PARENTS_STUDENTS = createIdentity(ParentsStudents.PARENTS_STUDENTS, ParentsStudents.PARENTS_STUDENTS.ID);
        public static Identity<PeriodsRecord, Integer> IDENTITY_PERIODS = createIdentity(Periods.PERIODS, Periods.PERIODS.ID);
        public static Identity<PeriodNotesRecord, Integer> IDENTITY_PERIOD_NOTES = createIdentity(PeriodNotes.PERIOD_NOTES, PeriodNotes.PERIOD_NOTES.ID);
        public static Identity<SchoolDataRecord, Integer> IDENTITY_SCHOOL_DATA = createIdentity(SchoolData.SCHOOL_DATA, SchoolData.SCHOOL_DATA.ID);
        public static Identity<StudentsRecord, Integer> IDENTITY_STUDENTS = createIdentity(Students.STUDENTS, Students.STUDENTS.ID);
        public static Identity<StudentsCoursesRecord, Integer> IDENTITY_STUDENTS_COURSES = createIdentity(StudentsCourses.STUDENTS_COURSES, StudentsCourses.STUDENTS_COURSES.ID);
        public static Identity<StudentsCoursesAssignmentsRecord, Integer> IDENTITY_STUDENTS_COURSES_ASSIGNMENTS = createIdentity(StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS, StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ID);
        public static Identity<StudentsCoursesExamsRecord, Integer> IDENTITY_STUDENTS_COURSES_EXAMS = createIdentity(StudentsCoursesExams.STUDENTS_COURSES_EXAMS, StudentsCoursesExams.STUDENTS_COURSES_EXAMS.ID);
        public static Identity<SubjectsRecord, Integer> IDENTITY_SUBJECTS = createIdentity(Subjects.SUBJECTS, Subjects.SUBJECTS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AssignmentsRecord> KEY_ASSIGNMENTS_PRIMARY = createUniqueKey(Assignments.ASSIGNMENTS, "KEY_assignments_PRIMARY", Assignments.ASSIGNMENTS.ID);
        public static final UniqueKey<AssignmentsCoursesRecord> KEY_ASSIGNMENTS_COURSES_PRIMARY = createUniqueKey(AssignmentsCourses.ASSIGNMENTS_COURSES, "KEY_assignments_courses_PRIMARY", AssignmentsCourses.ASSIGNMENTS_COURSES.ID);
        public static final UniqueKey<AttendancesRecord> KEY_ATTENDANCES_PRIMARY = createUniqueKey(Attendances.ATTENDANCES, "KEY_attendances_PRIMARY", Attendances.ATTENDANCES.ID);
        public static final UniqueKey<ClassesRecord> KEY_CLASSES_PRIMARY = createUniqueKey(Classes.CLASSES, "KEY_classes_PRIMARY", Classes.CLASSES.ID);
        public static final UniqueKey<ClassNewsRecord> KEY_CLASS_NEWS_PRIMARY = createUniqueKey(ClassNews.CLASS_NEWS, "KEY_class_news_PRIMARY", ClassNews.CLASS_NEWS.ID);
        public static final UniqueKey<CoursesRecord> KEY_COURSES_PRIMARY = createUniqueKey(Courses.COURSES, "KEY_courses_PRIMARY", Courses.COURSES.ID);
        public static final UniqueKey<CourseNewsRecord> KEY_COURSE_NEWS_PRIMARY = createUniqueKey(CourseNews.COURSE_NEWS, "KEY_course_news_PRIMARY", CourseNews.COURSE_NEWS.ID);
        public static final UniqueKey<CourseNotesRecord> KEY_COURSE_NOTES_PRIMARY = createUniqueKey(CourseNotes.COURSE_NOTES, "KEY_course_notes_PRIMARY", CourseNotes.COURSE_NOTES.ID);
        public static final UniqueKey<ExamsRecord> KEY_EXAMS_PRIMARY = createUniqueKey(Exams.EXAMS, "KEY_exams_PRIMARY", Exams.EXAMS.ID);
        public static final UniqueKey<ExamsCoursesRecord> KEY_EXAMS_COURSES_PRIMARY = createUniqueKey(ExamsCourses.EXAMS_COURSES, "KEY_exams_courses_PRIMARY", ExamsCourses.EXAMS_COURSES.ID);
        public static final UniqueKey<GradesRecord> KEY_GRADES_PRIMARY = createUniqueKey(Grades.GRADES, "KEY_grades_PRIMARY", Grades.GRADES.ID);
        public static final UniqueKey<HolidaysRecord> KEY_HOLIDAYS_PRIMARY = createUniqueKey(Holidays.HOLIDAYS, "KEY_holidays_PRIMARY", Holidays.HOLIDAYS.ID);
        public static final UniqueKey<LecturersRecord> KEY_LECTURERS_PRIMARY = createUniqueKey(Lecturers.LECTURERS, "KEY_lecturers_PRIMARY", Lecturers.LECTURERS.ID);
        public static final UniqueKey<LecturersRecord> KEY_LECTURERS_REGNUMBER_UNIQUE = createUniqueKey(Lecturers.LECTURERS, "KEY_lecturers_regNumber_UNIQUE", Lecturers.LECTURERS.REG_NUMBER);
        public static final UniqueKey<LecturersCoursesRecord> KEY_LECTURERS_COURSES_PRIMARY = createUniqueKey(LecturersCourses.LECTURERS_COURSES, "KEY_lecturers_courses_PRIMARY", LecturersCourses.LECTURERS_COURSES.LECTURER_ID, LecturersCourses.LECTURERS_COURSES.COURSE_ID);
        public static final UniqueKey<NewsRecord> KEY_NEWS_PRIMARY = createUniqueKey(News.NEWS, "KEY_news_PRIMARY", News.NEWS.ID);
        public static final UniqueKey<NotesRecord> KEY_NOTES_PRIMARY = createUniqueKey(Notes.NOTES, "KEY_notes_PRIMARY", Notes.NOTES.ID);
        public static final UniqueKey<ParentsRecord> KEY_PARENTS_PRIMARY = createUniqueKey(Parents.PARENTS, "KEY_parents_PRIMARY", Parents.PARENTS.ID);
        public static final UniqueKey<ParentsRecord> KEY_PARENTS_EMAIL = createUniqueKey(Parents.PARENTS, "KEY_parents_email", Parents.PARENTS.EMAIL);
        public static final UniqueKey<ParentsRecord> KEY_PARENTS_REGNUMBER_UNIQUE = createUniqueKey(Parents.PARENTS, "KEY_parents_regNumber_UNIQUE", Parents.PARENTS.REG_NUMBER);
        public static final UniqueKey<ParentsStudentsRecord> KEY_PARENTS_STUDENTS_PRIMARY = createUniqueKey(ParentsStudents.PARENTS_STUDENTS, "KEY_parents_students_PRIMARY", ParentsStudents.PARENTS_STUDENTS.ID);
        public static final UniqueKey<PeriodsRecord> KEY_PERIODS_PRIMARY = createUniqueKey(Periods.PERIODS, "KEY_periods_PRIMARY", Periods.PERIODS.ID);
        public static final UniqueKey<PeriodNotesRecord> KEY_PERIOD_NOTES_PRIMARY = createUniqueKey(PeriodNotes.PERIOD_NOTES, "KEY_period_notes_PRIMARY", PeriodNotes.PERIOD_NOTES.ID);
        public static final UniqueKey<SchoolDataRecord> KEY_SCHOOL_DATA_PRIMARY = createUniqueKey(SchoolData.SCHOOL_DATA, "KEY_school_data_PRIMARY", SchoolData.SCHOOL_DATA.ID);
        public static final UniqueKey<StudentsRecord> KEY_STUDENTS_PRIMARY = createUniqueKey(Students.STUDENTS, "KEY_students_PRIMARY", Students.STUDENTS.ID);
        public static final UniqueKey<StudentsRecord> KEY_STUDENTS_REGNUMBER_UNIQUE = createUniqueKey(Students.STUDENTS, "KEY_students_regNumber_UNIQUE", Students.STUDENTS.REG_NUMBER);
        public static final UniqueKey<StudentsCoursesRecord> KEY_STUDENTS_COURSES_PRIMARY = createUniqueKey(StudentsCourses.STUDENTS_COURSES, "KEY_students_courses_PRIMARY", StudentsCourses.STUDENTS_COURSES.ID);
        public static final UniqueKey<StudentsCoursesAssignmentsRecord> KEY_STUDENTS_COURSES_ASSIGNMENTS_PRIMARY = createUniqueKey(StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS, "KEY_students_courses_assignments_PRIMARY", StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ID);
        public static final UniqueKey<StudentsCoursesExamsRecord> KEY_STUDENTS_COURSES_EXAMS_PRIMARY = createUniqueKey(StudentsCoursesExams.STUDENTS_COURSES_EXAMS, "KEY_students_courses_exams_PRIMARY", StudentsCoursesExams.STUDENTS_COURSES_EXAMS.ID);
        public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_PRIMARY = createUniqueKey(Subjects.SUBJECTS, "KEY_subjects_PRIMARY", Subjects.SUBJECTS.ID);
        public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_NAME = createUniqueKey(Subjects.SUBJECTS, "KEY_subjects_name", Subjects.SUBJECTS.NAME);
        public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_SHORT_NAME = createUniqueKey(Subjects.SUBJECTS, "KEY_subjects_short_name", Subjects.SUBJECTS.SHORT_NAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AssignmentsRecord, LecturersRecord> FK_ASSIGNMENT_LECTURER1 = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, Assignments.ASSIGNMENTS, "fk_assignment_lecturer1", Assignments.ASSIGNMENTS.LECTURER_ID);
        public static final ForeignKey<AssignmentsCoursesRecord, AssignmentsRecord> FK_ASSIGNMENTS_COURSES_ASIGNMENT = createForeignKey(com.ivo.school.Keys.KEY_ASSIGNMENTS_PRIMARY, AssignmentsCourses.ASSIGNMENTS_COURSES, "fk_assignments_courses_asignment", AssignmentsCourses.ASSIGNMENTS_COURSES.ASSIGNMENT_ID);
        public static final ForeignKey<AssignmentsCoursesRecord, CoursesRecord> FK_ASSIGNMENTS_COURSES_COURSE = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, AssignmentsCourses.ASSIGNMENTS_COURSES, "fk_assignments_courses_course", AssignmentsCourses.ASSIGNMENTS_COURSES.COURSE_ID);
        public static final ForeignKey<AttendancesRecord, StudentsRecord> FK_ATTENDANCE_STUDENTS = createForeignKey(com.ivo.school.Keys.KEY_STUDENTS_PRIMARY, Attendances.ATTENDANCES, "fk_attendance_students", Attendances.ATTENDANCES.STUDENT_ID);
        public static final ForeignKey<AttendancesRecord, PeriodsRecord> FK_ATTENDANCE_PERIODS = createForeignKey(com.ivo.school.Keys.KEY_PERIODS_PRIMARY, Attendances.ATTENDANCES, "fk_attendance_periods", Attendances.ATTENDANCES.PERIOD_ID);
        public static final ForeignKey<ClassesRecord, LecturersRecord> FK_CLASS_LECTURER1 = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, Classes.CLASSES, "fk_class_lecturer1", Classes.CLASSES.LECTURER_ID);
        public static final ForeignKey<ClassesRecord, LecturersRecord> LECTURER_ID = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, Classes.CLASSES, "lecturer_id", Classes.CLASSES.LECTURER_ID);
        public static final ForeignKey<CoursesRecord, ClassesRecord> FK_CLASS_HAS_SUBJECT_CLASS2 = createForeignKey(com.ivo.school.Keys.KEY_CLASSES_PRIMARY, Courses.COURSES, "fk_class_has_subject_class2", Courses.COURSES.CLASS_ID);
        public static final ForeignKey<CoursesRecord, SubjectsRecord> FK_CLASS_HAS_SUBJECT_SUBJECT2 = createForeignKey(com.ivo.school.Keys.KEY_SUBJECTS_PRIMARY, Courses.COURSES, "fk_class_has_subject_subject2", Courses.COURSES.SUBJECT_ID);
        public static final ForeignKey<CourseNewsRecord, CoursesRecord> FK_COURSE_NEWS_COURSE = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, CourseNews.COURSE_NEWS, "fk_course_news_course", CourseNews.COURSE_NEWS.COURSE_ID);
        public static final ForeignKey<CourseNewsRecord, NewsRecord> FK_COURSE_NEWS_NEWS = createForeignKey(com.ivo.school.Keys.KEY_NEWS_PRIMARY, CourseNews.COURSE_NEWS, "fk_course_news_news", CourseNews.COURSE_NEWS.NEWS_ID);
        public static final ForeignKey<CourseNotesRecord, NotesRecord> FK_COURSE_NOTES_NOTES = createForeignKey(com.ivo.school.Keys.KEY_NOTES_PRIMARY, CourseNotes.COURSE_NOTES, "fk_course_notes_notes", CourseNotes.COURSE_NOTES.NOTE_ID);
        public static final ForeignKey<CourseNotesRecord, CoursesRecord> FK_COURSE_NOTES_COURSES = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, CourseNotes.COURSE_NOTES, "fk_course_notes_courses", CourseNotes.COURSE_NOTES.COURSE_ID);
        public static final ForeignKey<ExamsCoursesRecord, ExamsRecord> FK_EXAMS_COURSES_EXAMS = createForeignKey(com.ivo.school.Keys.KEY_EXAMS_PRIMARY, ExamsCourses.EXAMS_COURSES, "fk_exams_courses_exams", ExamsCourses.EXAMS_COURSES.EXAM_ID);
        public static final ForeignKey<ExamsCoursesRecord, CoursesRecord> FK_EXAMS_COURSES_COURSE = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, ExamsCourses.EXAMS_COURSES, "fk_exams_courses_course", ExamsCourses.EXAMS_COURSES.COURSE_ID);
        public static final ForeignKey<LecturersCoursesRecord, LecturersRecord> FK_LECTURER_HAS_COURSE_LECTURER1 = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, LecturersCourses.LECTURERS_COURSES, "fk_lecturer_has_course_lecturer1", LecturersCourses.LECTURERS_COURSES.LECTURER_ID);
        public static final ForeignKey<LecturersCoursesRecord, CoursesRecord> FK_LECTURER_HAS_COURSE_COURSE1 = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, LecturersCourses.LECTURERS_COURSES, "fk_lecturer_has_course_course1", LecturersCourses.LECTURERS_COURSES.COURSE_ID);
        public static final ForeignKey<NewsRecord, LecturersRecord> FK_NEWS_LECTURER1 = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, News.NEWS, "fk_news_lecturer1", News.NEWS.LECTURER_ID);
        public static final ForeignKey<NotesRecord, LecturersRecord> FK_NOTES_LECTURERS = createForeignKey(com.ivo.school.Keys.KEY_LECTURERS_PRIMARY, Notes.NOTES, "fk_notes_lecturers", Notes.NOTES.LECTURER_ID);
        public static final ForeignKey<ParentsStudentsRecord, ParentsRecord> FK_PARENT_HAS_STUDENT_PARENT = createForeignKey(com.ivo.school.Keys.KEY_PARENTS_PRIMARY, ParentsStudents.PARENTS_STUDENTS, "fk_parent_has_student_parent", ParentsStudents.PARENTS_STUDENTS.PARENT_ID);
        public static final ForeignKey<ParentsStudentsRecord, StudentsRecord> FK_PARENT_HAS_STUDENT_STUDENT1 = createForeignKey(com.ivo.school.Keys.KEY_STUDENTS_PRIMARY, ParentsStudents.PARENTS_STUDENTS, "fk_parent_has_student_student1", ParentsStudents.PARENTS_STUDENTS.STUDENT_ID);
        public static final ForeignKey<PeriodsRecord, CoursesRecord> FK_PERIOD_COURSE1 = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, Periods.PERIODS, "fk_period_course1", Periods.PERIODS.COURSE_ID);
        public static final ForeignKey<PeriodNotesRecord, NotesRecord> FK_PERIOD_NOTES_NOTES = createForeignKey(com.ivo.school.Keys.KEY_NOTES_PRIMARY, PeriodNotes.PERIOD_NOTES, "fk_period_notes_notes", PeriodNotes.PERIOD_NOTES.NOTE_ID);
        public static final ForeignKey<PeriodNotesRecord, PeriodsRecord> FK_PERIOD_NOTES_PERIODS = createForeignKey(com.ivo.school.Keys.KEY_PERIODS_PRIMARY, PeriodNotes.PERIOD_NOTES, "fk_period_notes_periods", PeriodNotes.PERIOD_NOTES.PERIOD_ID);
        public static final ForeignKey<StudentsRecord, ClassesRecord> FK_STUDENTS_CLASSES = createForeignKey(com.ivo.school.Keys.KEY_CLASSES_PRIMARY, Students.STUDENTS, "fk_students_classes", Students.STUDENTS.CLASS_ID);
        public static final ForeignKey<StudentsCoursesRecord, StudentsRecord> FK_STUDENT_HAS_COURSE_STUDENT1 = createForeignKey(com.ivo.school.Keys.KEY_STUDENTS_PRIMARY, StudentsCourses.STUDENTS_COURSES, "fk_student_has_course_student1", StudentsCourses.STUDENTS_COURSES.STUDENT_ID);
        public static final ForeignKey<StudentsCoursesRecord, CoursesRecord> FK_STUDENT_HAS_COURSE_COURSE1 = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, StudentsCourses.STUDENTS_COURSES, "fk_student_has_course_course1", StudentsCourses.STUDENTS_COURSES.COURSE_ID);
        public static final ForeignKey<StudentsCoursesAssignmentsRecord, StudentsRecord> FK_STUDENT_COURSES_ASSIGNMENT_STUDENT = createForeignKey(com.ivo.school.Keys.KEY_STUDENTS_PRIMARY, StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS, "fk_student_courses_assignment_student", StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.STUDENT_ID);
        public static final ForeignKey<StudentsCoursesAssignmentsRecord, CoursesRecord> FK_STUDENT_COURSES_ASSIGNMENT_COURSE = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS, "fk_student_courses_assignment_course", StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.COURSE_ID);
        public static final ForeignKey<StudentsCoursesAssignmentsRecord, AssignmentsRecord> FK_STUDENT_COURSES_ASSIGNMENT_ASSIGNMENT1 = createForeignKey(com.ivo.school.Keys.KEY_ASSIGNMENTS_PRIMARY, StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS, "fk_student_courses_assignment_assignment1", StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ASSIGNMENT_ID);
        public static final ForeignKey<StudentsCoursesExamsRecord, StudentsRecord> FK_STUDENT = createForeignKey(com.ivo.school.Keys.KEY_STUDENTS_PRIMARY, StudentsCoursesExams.STUDENTS_COURSES_EXAMS, "fk_student", StudentsCoursesExams.STUDENTS_COURSES_EXAMS.STUDENT_ID);
        public static final ForeignKey<StudentsCoursesExamsRecord, CoursesRecord> FK_COURSE = createForeignKey(com.ivo.school.Keys.KEY_COURSES_PRIMARY, StudentsCoursesExams.STUDENTS_COURSES_EXAMS, "fk_course", StudentsCoursesExams.STUDENTS_COURSES_EXAMS.COURSE_ID);
        public static final ForeignKey<StudentsCoursesExamsRecord, ExamsRecord> FK_EXAM = createForeignKey(com.ivo.school.Keys.KEY_EXAMS_PRIMARY, StudentsCoursesExams.STUDENTS_COURSES_EXAMS, "fk_exam", StudentsCoursesExams.STUDENTS_COURSES_EXAMS.EXAM_ID);
    }
}
