/**
 * This class is generated by jOOQ
 */
package com.ivo.school;


import com.ivo.school.tables.Assignments;
import com.ivo.school.tables.AssignmentsCourses;
import com.ivo.school.tables.Attendances;
import com.ivo.school.tables.ClassNews;
import com.ivo.school.tables.Classes;
import com.ivo.school.tables.CourseNews;
import com.ivo.school.tables.CourseNotes;
import com.ivo.school.tables.Courses;
import com.ivo.school.tables.Exams;
import com.ivo.school.tables.ExamsCourses;
import com.ivo.school.tables.Grades;
import com.ivo.school.tables.Holidays;
import com.ivo.school.tables.Lecturers;
import com.ivo.school.tables.LecturersCourses;
import com.ivo.school.tables.News;
import com.ivo.school.tables.Notes;
import com.ivo.school.tables.Parents;
import com.ivo.school.tables.ParentsStudents;
import com.ivo.school.tables.PeriodNotes;
import com.ivo.school.tables.Periods;
import com.ivo.school.tables.SchoolData;
import com.ivo.school.tables.Students;
import com.ivo.school.tables.StudentsCourses;
import com.ivo.school.tables.StudentsCoursesAssignments;
import com.ivo.school.tables.StudentsCoursesExams;
import com.ivo.school.tables.Subjects;
import com.ivo.school.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends SchemaImpl {

    private static final long serialVersionUID = -1085785046;

    /**
     * The reference instance of <code>mydb</code>
     */
    public static final Mydb MYDB = new Mydb();

    /**
     * The table <code>mydb.assignments</code>.
     */
    public final Assignments ASSIGNMENTS = com.ivo.school.tables.Assignments.ASSIGNMENTS;

    /**
     * The table <code>mydb.assignments_courses</code>.
     */
    public final AssignmentsCourses ASSIGNMENTS_COURSES = com.ivo.school.tables.AssignmentsCourses.ASSIGNMENTS_COURSES;

    /**
     * The table <code>mydb.attendances</code>.
     */
    public final Attendances ATTENDANCES = com.ivo.school.tables.Attendances.ATTENDANCES;

    /**
     * The table <code>mydb.classes</code>.
     */
    public final Classes CLASSES = com.ivo.school.tables.Classes.CLASSES;

    /**
     * The table <code>mydb.class_news</code>.
     */
    public final ClassNews CLASS_NEWS = com.ivo.school.tables.ClassNews.CLASS_NEWS;

    /**
     * The table <code>mydb.courses</code>.
     */
    public final Courses COURSES = com.ivo.school.tables.Courses.COURSES;

    /**
     * The table <code>mydb.course_news</code>.
     */
    public final CourseNews COURSE_NEWS = com.ivo.school.tables.CourseNews.COURSE_NEWS;

    /**
     * The table <code>mydb.course_notes</code>.
     */
    public final CourseNotes COURSE_NOTES = com.ivo.school.tables.CourseNotes.COURSE_NOTES;

    /**
     * The table <code>mydb.exams</code>.
     */
    public final Exams EXAMS = com.ivo.school.tables.Exams.EXAMS;

    /**
     * The table <code>mydb.exams_courses</code>.
     */
    public final ExamsCourses EXAMS_COURSES = com.ivo.school.tables.ExamsCourses.EXAMS_COURSES;

    /**
     * The table <code>mydb.grades</code>.
     */
    public final Grades GRADES = com.ivo.school.tables.Grades.GRADES;

    /**
     * The table <code>mydb.holidays</code>.
     */
    public final Holidays HOLIDAYS = com.ivo.school.tables.Holidays.HOLIDAYS;

    /**
     * The table <code>mydb.lecturers</code>.
     */
    public final Lecturers LECTURERS = com.ivo.school.tables.Lecturers.LECTURERS;

    /**
     * The table <code>mydb.lecturers_courses</code>.
     */
    public final LecturersCourses LECTURERS_COURSES = com.ivo.school.tables.LecturersCourses.LECTURERS_COURSES;

    /**
     * The table <code>mydb.news</code>.
     */
    public final News NEWS = com.ivo.school.tables.News.NEWS;

    /**
     * The table <code>mydb.notes</code>.
     */
    public final Notes NOTES = com.ivo.school.tables.Notes.NOTES;

    /**
     * The table <code>mydb.parents</code>.
     */
    public final Parents PARENTS = com.ivo.school.tables.Parents.PARENTS;

    /**
     * The table <code>mydb.parents_students</code>.
     */
    public final ParentsStudents PARENTS_STUDENTS = com.ivo.school.tables.ParentsStudents.PARENTS_STUDENTS;

    /**
     * The table <code>mydb.periods</code>.
     */
    public final Periods PERIODS = com.ivo.school.tables.Periods.PERIODS;

    /**
     * The table <code>mydb.period_notes</code>.
     */
    public final PeriodNotes PERIOD_NOTES = com.ivo.school.tables.PeriodNotes.PERIOD_NOTES;

    /**
     * The table <code>mydb.school_data</code>.
     */
    public final SchoolData SCHOOL_DATA = com.ivo.school.tables.SchoolData.SCHOOL_DATA;

    /**
     * The table <code>mydb.students</code>.
     */
    public final Students STUDENTS = com.ivo.school.tables.Students.STUDENTS;

    /**
     * The table <code>mydb.students_courses</code>.
     */
    public final StudentsCourses STUDENTS_COURSES = com.ivo.school.tables.StudentsCourses.STUDENTS_COURSES;

    /**
     * The table <code>mydb.students_courses_assignments</code>.
     */
    public final StudentsCoursesAssignments STUDENTS_COURSES_ASSIGNMENTS = com.ivo.school.tables.StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS;

    /**
     * The table <code>mydb.students_courses_exams</code>.
     */
    public final StudentsCoursesExams STUDENTS_COURSES_EXAMS = com.ivo.school.tables.StudentsCoursesExams.STUDENTS_COURSES_EXAMS;

    /**
     * The table <code>mydb.subjects</code>.
     */
    public final Subjects SUBJECTS = com.ivo.school.tables.Subjects.SUBJECTS;

    /**
     * VIEW
     */
    public final Users USERS = com.ivo.school.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Mydb() {
        super("mydb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Assignments.ASSIGNMENTS,
            AssignmentsCourses.ASSIGNMENTS_COURSES,
            Attendances.ATTENDANCES,
            Classes.CLASSES,
            ClassNews.CLASS_NEWS,
            Courses.COURSES,
            CourseNews.COURSE_NEWS,
            CourseNotes.COURSE_NOTES,
            Exams.EXAMS,
            ExamsCourses.EXAMS_COURSES,
            Grades.GRADES,
            Holidays.HOLIDAYS,
            Lecturers.LECTURERS,
            LecturersCourses.LECTURERS_COURSES,
            News.NEWS,
            Notes.NOTES,
            Parents.PARENTS,
            ParentsStudents.PARENTS_STUDENTS,
            Periods.PERIODS,
            PeriodNotes.PERIOD_NOTES,
            SchoolData.SCHOOL_DATA,
            Students.STUDENTS,
            StudentsCourses.STUDENTS_COURSES,
            StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS,
            StudentsCoursesExams.STUDENTS_COURSES_EXAMS,
            Subjects.SUBJECTS,
            Users.USERS);
    }
}
