/**
 * This class is generated by jOOQ
 */
package com.ivo.school;


import com.ivo.school.tables.Assignments;
import com.ivo.school.tables.AssignmentsCourses;
import com.ivo.school.tables.Attendances;
import com.ivo.school.tables.ClassNews;
import com.ivo.school.tables.Classes;
import com.ivo.school.tables.CourseNews;
import com.ivo.school.tables.CourseNotes;
import com.ivo.school.tables.Courses;
import com.ivo.school.tables.Exams;
import com.ivo.school.tables.ExamsCourses;
import com.ivo.school.tables.Grades;
import com.ivo.school.tables.Holidays;
import com.ivo.school.tables.Lecturers;
import com.ivo.school.tables.LecturersCourses;
import com.ivo.school.tables.News;
import com.ivo.school.tables.Notes;
import com.ivo.school.tables.Parents;
import com.ivo.school.tables.ParentsStudents;
import com.ivo.school.tables.PeriodNotes;
import com.ivo.school.tables.Periods;
import com.ivo.school.tables.SchoolData;
import com.ivo.school.tables.Students;
import com.ivo.school.tables.StudentsCourses;
import com.ivo.school.tables.StudentsCoursesAssignments;
import com.ivo.school.tables.StudentsCoursesExams;
import com.ivo.school.tables.Subjects;
import com.ivo.school.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mydb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mydb.assignments</code>.
     */
    public static final Assignments ASSIGNMENTS = com.ivo.school.tables.Assignments.ASSIGNMENTS;

    /**
     * The table <code>mydb.assignments_courses</code>.
     */
    public static final AssignmentsCourses ASSIGNMENTS_COURSES = com.ivo.school.tables.AssignmentsCourses.ASSIGNMENTS_COURSES;

    /**
     * The table <code>mydb.attendances</code>.
     */
    public static final Attendances ATTENDANCES = com.ivo.school.tables.Attendances.ATTENDANCES;

    /**
     * The table <code>mydb.classes</code>.
     */
    public static final Classes CLASSES = com.ivo.school.tables.Classes.CLASSES;

    /**
     * The table <code>mydb.class_news</code>.
     */
    public static final ClassNews CLASS_NEWS = com.ivo.school.tables.ClassNews.CLASS_NEWS;

    /**
     * The table <code>mydb.courses</code>.
     */
    public static final Courses COURSES = com.ivo.school.tables.Courses.COURSES;

    /**
     * The table <code>mydb.course_news</code>.
     */
    public static final CourseNews COURSE_NEWS = com.ivo.school.tables.CourseNews.COURSE_NEWS;

    /**
     * The table <code>mydb.course_notes</code>.
     */
    public static final CourseNotes COURSE_NOTES = com.ivo.school.tables.CourseNotes.COURSE_NOTES;

    /**
     * The table <code>mydb.exams</code>.
     */
    public static final Exams EXAMS = com.ivo.school.tables.Exams.EXAMS;

    /**
     * The table <code>mydb.exams_courses</code>.
     */
    public static final ExamsCourses EXAMS_COURSES = com.ivo.school.tables.ExamsCourses.EXAMS_COURSES;

    /**
     * The table <code>mydb.grades</code>.
     */
    public static final Grades GRADES = com.ivo.school.tables.Grades.GRADES;

    /**
     * The table <code>mydb.holidays</code>.
     */
    public static final Holidays HOLIDAYS = com.ivo.school.tables.Holidays.HOLIDAYS;

    /**
     * The table <code>mydb.lecturers</code>.
     */
    public static final Lecturers LECTURERS = com.ivo.school.tables.Lecturers.LECTURERS;

    /**
     * The table <code>mydb.lecturers_courses</code>.
     */
    public static final LecturersCourses LECTURERS_COURSES = com.ivo.school.tables.LecturersCourses.LECTURERS_COURSES;

    /**
     * The table <code>mydb.news</code>.
     */
    public static final News NEWS = com.ivo.school.tables.News.NEWS;

    /**
     * The table <code>mydb.notes</code>.
     */
    public static final Notes NOTES = com.ivo.school.tables.Notes.NOTES;

    /**
     * The table <code>mydb.parents</code>.
     */
    public static final Parents PARENTS = com.ivo.school.tables.Parents.PARENTS;

    /**
     * The table <code>mydb.parents_students</code>.
     */
    public static final ParentsStudents PARENTS_STUDENTS = com.ivo.school.tables.ParentsStudents.PARENTS_STUDENTS;

    /**
     * The table <code>mydb.periods</code>.
     */
    public static final Periods PERIODS = com.ivo.school.tables.Periods.PERIODS;

    /**
     * The table <code>mydb.period_notes</code>.
     */
    public static final PeriodNotes PERIOD_NOTES = com.ivo.school.tables.PeriodNotes.PERIOD_NOTES;

    /**
     * The table <code>mydb.school_data</code>.
     */
    public static final SchoolData SCHOOL_DATA = com.ivo.school.tables.SchoolData.SCHOOL_DATA;

    /**
     * The table <code>mydb.students</code>.
     */
    public static final Students STUDENTS = com.ivo.school.tables.Students.STUDENTS;

    /**
     * The table <code>mydb.students_courses</code>.
     */
    public static final StudentsCourses STUDENTS_COURSES = com.ivo.school.tables.StudentsCourses.STUDENTS_COURSES;

    /**
     * The table <code>mydb.students_courses_assignments</code>.
     */
    public static final StudentsCoursesAssignments STUDENTS_COURSES_ASSIGNMENTS = com.ivo.school.tables.StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS;

    /**
     * The table <code>mydb.students_courses_exams</code>.
     */
    public static final StudentsCoursesExams STUDENTS_COURSES_EXAMS = com.ivo.school.tables.StudentsCoursesExams.STUDENTS_COURSES_EXAMS;

    /**
     * The table <code>mydb.subjects</code>.
     */
    public static final Subjects SUBJECTS = com.ivo.school.tables.Subjects.SUBJECTS;

    /**
     * VIEW
     */
    public static final Users USERS = com.ivo.school.tables.Users.USERS;
}
