/**
 * This class is generated by jOOQ
 */
package com.ivo;


import com.ivo.tables.Assignments;
import com.ivo.tables.AssignmentsCourses;
import com.ivo.tables.Attendances;
import com.ivo.tables.ClassNews;
import com.ivo.tables.Classes;
import com.ivo.tables.CourseNews;
import com.ivo.tables.CourseNotes;
import com.ivo.tables.Courses;
import com.ivo.tables.Exams;
import com.ivo.tables.ExamsCourses;
import com.ivo.tables.Grades;
import com.ivo.tables.Holidays;
import com.ivo.tables.Lecturers;
import com.ivo.tables.LecturersCourses;
import com.ivo.tables.News;
import com.ivo.tables.Notes;
import com.ivo.tables.Parents;
import com.ivo.tables.ParentsStudents;
import com.ivo.tables.PeriodNotes;
import com.ivo.tables.Periods;
import com.ivo.tables.SchoolData;
import com.ivo.tables.Students;
import com.ivo.tables.StudentsCourses;
import com.ivo.tables.StudentsCoursesAssignments;
import com.ivo.tables.StudentsCoursesExams;
import com.ivo.tables.Subjects;
import com.ivo.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ivoschool extends SchemaImpl {

    private static final long serialVersionUID = -192207596;

    /**
     * The reference instance of <code>ivoschool</code>
     */
    public static final Ivoschool IVOSCHOOL = new Ivoschool();

    /**
     * The table <code>ivoschool.assignments</code>.
     */
    public final Assignments ASSIGNMENTS = Assignments.ASSIGNMENTS;

    /**
     * The table <code>ivoschool.assignments_courses</code>.
     */
    public final AssignmentsCourses ASSIGNMENTS_COURSES = AssignmentsCourses.ASSIGNMENTS_COURSES;

    /**
     * The table <code>ivoschool.attendances</code>.
     */
    public final Attendances ATTENDANCES = Attendances.ATTENDANCES;

    /**
     * The table <code>ivoschool.classes</code>.
     */
    public final Classes CLASSES = Classes.CLASSES;

    /**
     * The table <code>ivoschool.class_news</code>.
     */
    public final ClassNews CLASS_NEWS = ClassNews.CLASS_NEWS;

    /**
     * The table <code>ivoschool.courses</code>.
     */
    public final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>ivoschool.course_news</code>.
     */
    public final CourseNews COURSE_NEWS = CourseNews.COURSE_NEWS;

    /**
     * The table <code>ivoschool.course_notes</code>.
     */
    public final CourseNotes COURSE_NOTES = CourseNotes.COURSE_NOTES;

    /**
     * The table <code>ivoschool.exams</code>.
     */
    public final Exams EXAMS = Exams.EXAMS;

    /**
     * The table <code>ivoschool.exams_courses</code>.
     */
    public final ExamsCourses EXAMS_COURSES = ExamsCourses.EXAMS_COURSES;

    /**
     * The table <code>ivoschool.grades</code>.
     */
    public final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>ivoschool.holidays</code>.
     */
    public final Holidays HOLIDAYS = Holidays.HOLIDAYS;

    /**
     * The table <code>ivoschool.lecturers</code>.
     */
    public final Lecturers LECTURERS = Lecturers.LECTURERS;

    /**
     * The table <code>ivoschool.lecturers_courses</code>.
     */
    public final LecturersCourses LECTURERS_COURSES = LecturersCourses.LECTURERS_COURSES;

    /**
     * The table <code>ivoschool.news</code>.
     */
    public final News NEWS = News.NEWS;

    /**
     * The table <code>ivoschool.notes</code>.
     */
    public final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>ivoschool.parents</code>.
     */
    public final Parents PARENTS = Parents.PARENTS;

    /**
     * The table <code>ivoschool.parents_students</code>.
     */
    public final ParentsStudents PARENTS_STUDENTS = ParentsStudents.PARENTS_STUDENTS;

    /**
     * The table <code>ivoschool.periods</code>.
     */
    public final Periods PERIODS = Periods.PERIODS;

    /**
     * The table <code>ivoschool.period_notes</code>.
     */
    public final PeriodNotes PERIOD_NOTES = PeriodNotes.PERIOD_NOTES;

    /**
     * The table <code>ivoschool.school_data</code>.
     */
    public final SchoolData SCHOOL_DATA = SchoolData.SCHOOL_DATA;

    /**
     * The table <code>ivoschool.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>ivoschool.students_courses</code>.
     */
    public final StudentsCourses STUDENTS_COURSES = StudentsCourses.STUDENTS_COURSES;

    /**
     * The table <code>ivoschool.students_courses_assignments</code>.
     */
    public final StudentsCoursesAssignments STUDENTS_COURSES_ASSIGNMENTS = StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS;

    /**
     * The table <code>ivoschool.students_courses_exams</code>.
     */
    public final StudentsCoursesExams STUDENTS_COURSES_EXAMS = StudentsCoursesExams.STUDENTS_COURSES_EXAMS;

    /**
     * The table <code>ivoschool.subjects</code>.
     */
    public final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * VIEW
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Ivoschool() {
        super("ivoschool", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Assignments.ASSIGNMENTS,
            AssignmentsCourses.ASSIGNMENTS_COURSES,
            Attendances.ATTENDANCES,
            Classes.CLASSES,
            ClassNews.CLASS_NEWS,
            Courses.COURSES,
            CourseNews.COURSE_NEWS,
            CourseNotes.COURSE_NOTES,
            Exams.EXAMS,
            ExamsCourses.EXAMS_COURSES,
            Grades.GRADES,
            Holidays.HOLIDAYS,
            Lecturers.LECTURERS,
            LecturersCourses.LECTURERS_COURSES,
            News.NEWS,
            Notes.NOTES,
            Parents.PARENTS,
            ParentsStudents.PARENTS_STUDENTS,
            Periods.PERIODS,
            PeriodNotes.PERIOD_NOTES,
            SchoolData.SCHOOL_DATA,
            Students.STUDENTS,
            StudentsCourses.STUDENTS_COURSES,
            StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS,
            StudentsCoursesExams.STUDENTS_COURSES_EXAMS,
            Subjects.SUBJECTS,
            Users.USERS);
    }
}
