/**
 * This class is generated by jOOQ
 */
package com.ivo;


import com.ivo.tables.Assignments;
import com.ivo.tables.AssignmentsCourses;
import com.ivo.tables.Attendances;
import com.ivo.tables.ClassNews;
import com.ivo.tables.Classes;
import com.ivo.tables.CourseNews;
import com.ivo.tables.CourseNotes;
import com.ivo.tables.Courses;
import com.ivo.tables.Exams;
import com.ivo.tables.ExamsCourses;
import com.ivo.tables.Grades;
import com.ivo.tables.Holidays;
import com.ivo.tables.Lecturers;
import com.ivo.tables.LecturersCourses;
import com.ivo.tables.News;
import com.ivo.tables.Notes;
import com.ivo.tables.Parents;
import com.ivo.tables.ParentsStudents;
import com.ivo.tables.PeriodNotes;
import com.ivo.tables.Periods;
import com.ivo.tables.SchoolData;
import com.ivo.tables.Students;
import com.ivo.tables.StudentsCourses;
import com.ivo.tables.StudentsCoursesAssignments;
import com.ivo.tables.StudentsCoursesExams;
import com.ivo.tables.Subjects;
import com.ivo.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ivoschool
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ivoschool.assignments</code>.
     */
    public static final Assignments ASSIGNMENTS = Assignments.ASSIGNMENTS;

    /**
     * The table <code>ivoschool.assignments_courses</code>.
     */
    public static final AssignmentsCourses ASSIGNMENTS_COURSES = AssignmentsCourses.ASSIGNMENTS_COURSES;

    /**
     * The table <code>ivoschool.attendances</code>.
     */
    public static final Attendances ATTENDANCES = Attendances.ATTENDANCES;

    /**
     * The table <code>ivoschool.classes</code>.
     */
    public static final Classes CLASSES = Classes.CLASSES;

    /**
     * The table <code>ivoschool.class_news</code>.
     */
    public static final ClassNews CLASS_NEWS = ClassNews.CLASS_NEWS;

    /**
     * The table <code>ivoschool.courses</code>.
     */
    public static final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>ivoschool.course_news</code>.
     */
    public static final CourseNews COURSE_NEWS = CourseNews.COURSE_NEWS;

    /**
     * The table <code>ivoschool.course_notes</code>.
     */
    public static final CourseNotes COURSE_NOTES = CourseNotes.COURSE_NOTES;

    /**
     * The table <code>ivoschool.exams</code>.
     */
    public static final Exams EXAMS = Exams.EXAMS;

    /**
     * The table <code>ivoschool.exams_courses</code>.
     */
    public static final ExamsCourses EXAMS_COURSES = ExamsCourses.EXAMS_COURSES;

    /**
     * The table <code>ivoschool.grades</code>.
     */
    public static final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>ivoschool.holidays</code>.
     */
    public static final Holidays HOLIDAYS = Holidays.HOLIDAYS;

    /**
     * The table <code>ivoschool.lecturers</code>.
     */
    public static final Lecturers LECTURERS = Lecturers.LECTURERS;

    /**
     * The table <code>ivoschool.lecturers_courses</code>.
     */
    public static final LecturersCourses LECTURERS_COURSES = LecturersCourses.LECTURERS_COURSES;

    /**
     * The table <code>ivoschool.news</code>.
     */
    public static final News NEWS = News.NEWS;

    /**
     * The table <code>ivoschool.notes</code>.
     */
    public static final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>ivoschool.parents</code>.
     */
    public static final Parents PARENTS = Parents.PARENTS;

    /**
     * The table <code>ivoschool.parents_students</code>.
     */
    public static final ParentsStudents PARENTS_STUDENTS = ParentsStudents.PARENTS_STUDENTS;

    /**
     * The table <code>ivoschool.periods</code>.
     */
    public static final Periods PERIODS = Periods.PERIODS;

    /**
     * The table <code>ivoschool.period_notes</code>.
     */
    public static final PeriodNotes PERIOD_NOTES = PeriodNotes.PERIOD_NOTES;

    /**
     * The table <code>ivoschool.school_data</code>.
     */
    public static final SchoolData SCHOOL_DATA = SchoolData.SCHOOL_DATA;

    /**
     * The table <code>ivoschool.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>ivoschool.students_courses</code>.
     */
    public static final StudentsCourses STUDENTS_COURSES = StudentsCourses.STUDENTS_COURSES;

    /**
     * The table <code>ivoschool.students_courses_assignments</code>.
     */
    public static final StudentsCoursesAssignments STUDENTS_COURSES_ASSIGNMENTS = StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS;

    /**
     * The table <code>ivoschool.students_courses_exams</code>.
     */
    public static final StudentsCoursesExams STUDENTS_COURSES_EXAMS = StudentsCoursesExams.STUDENTS_COURSES_EXAMS;

    /**
     * The table <code>ivoschool.subjects</code>.
     */
    public static final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * VIEW
     */
    public static final Users USERS = Users.USERS;
}
