/**
 * This class is generated by jOOQ
 */
package com.ivo.tables;


import com.ivo.Ivoschool;
import com.ivo.Keys;
import com.ivo.tables.records.ClassNewsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassNews extends TableImpl<ClassNewsRecord> {

    private static final long serialVersionUID = 144015826;

    /**
     * The reference instance of <code>ivoschool.class_news</code>
     */
    public static final ClassNews CLASS_NEWS = new ClassNews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassNewsRecord> getRecordType() {
        return ClassNewsRecord.class;
    }

    /**
     * The column <code>ivoschool.class_news.id</code>.
     */
    public final TableField<ClassNewsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.class_news.class_id</code>.
     */
    public final TableField<ClassNewsRecord, Integer> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.class_news.news_id</code>.
     */
    public final TableField<ClassNewsRecord, Integer> NEWS_ID = createField("news_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.class_news.createdAt</code>.
     */
    public final TableField<ClassNewsRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>ivoschool.class_news.updatedAt</code>.
     */
    public final TableField<ClassNewsRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>ivoschool.class_news</code> table reference
     */
    public ClassNews() {
        this("class_news", null);
    }

    /**
     * Create an aliased <code>ivoschool.class_news</code> table reference
     */
    public ClassNews(String alias) {
        this(alias, CLASS_NEWS);
    }

    private ClassNews(String alias, Table<ClassNewsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClassNews(String alias, Table<ClassNewsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ivoschool.IVOSCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClassNewsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLASS_NEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassNewsRecord> getPrimaryKey() {
        return Keys.KEY_CLASS_NEWS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassNewsRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassNewsRecord>>asList(Keys.KEY_CLASS_NEWS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNews as(String alias) {
        return new ClassNews(alias, this);
    }

    /**
     * Rename this table
     */
    public ClassNews rename(String name) {
        return new ClassNews(name, null);
    }
}
