/**
 * This class is generated by jOOQ
 */
package com.ivo.tables;


import com.ivo.Ivoschool;
import com.ivo.Keys;
import com.ivo.tables.records.LecturersRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lecturers extends TableImpl<LecturersRecord> {

    private static final long serialVersionUID = -37179536;

    /**
     * The reference instance of <code>ivoschool.lecturers</code>
     */
    public static final Lecturers LECTURERS = new Lecturers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LecturersRecord> getRecordType() {
        return LecturersRecord.class;
    }

    /**
     * The column <code>ivoschool.lecturers.id</code>.
     */
    public final TableField<LecturersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.reg_number</code>.
     */
    public final TableField<LecturersRecord, String> REG_NUMBER = createField("reg_number", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.first_name</code>.
     */
    public final TableField<LecturersRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.last_name</code>.
     */
    public final TableField<LecturersRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.dob</code>.
     */
    public final TableField<LecturersRecord, String> DOB = createField("dob", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.qualification</code>.
     */
    public final TableField<LecturersRecord, String> QUALIFICATION = createField("qualification", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.photo_url</code>.
     */
    public final TableField<LecturersRecord, String> PHOTO_URL = createField("photo_url", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.lecturers.gender</code>.
     */
    public final TableField<LecturersRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.address</code>.
     */
    public final TableField<LecturersRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.phone_number</code>.
     */
    public final TableField<LecturersRecord, String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.email</code>.
     */
    public final TableField<LecturersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.nationality</code>.
     */
    public final TableField<LecturersRecord, String> NATIONALITY = createField("nationality", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.language</code>.
     */
    public final TableField<LecturersRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.lecturers.state_of_origin</code>.
     */
    public final TableField<LecturersRecord, String> STATE_OF_ORIGIN = createField("state_of_origin", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.lecturers.password</code>.
     */
    public final TableField<LecturersRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>ivoschool.lecturers.role</code>.
     */
    public final TableField<LecturersRecord, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("LECTURER", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ivoschool.lecturers.createdAt</code>.
     */
    public final TableField<LecturersRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ivoschool.lecturers.updatedAt</code>.
     */
    public final TableField<LecturersRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ivoschool.lecturers.previous_work_place</code>.
     */
    public final TableField<LecturersRecord, String> PREVIOUS_WORK_PLACE = createField("previous_work_place", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>ivoschool.lecturers</code> table reference
     */
    public Lecturers() {
        this("lecturers", null);
    }

    /**
     * Create an aliased <code>ivoschool.lecturers</code> table reference
     */
    public Lecturers(String alias) {
        this(alias, LECTURERS);
    }

    private Lecturers(String alias, Table<LecturersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Lecturers(String alias, Table<LecturersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ivoschool.IVOSCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LecturersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LECTURERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LecturersRecord> getPrimaryKey() {
        return Keys.KEY_LECTURERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LecturersRecord>> getKeys() {
        return Arrays.<UniqueKey<LecturersRecord>>asList(Keys.KEY_LECTURERS_PRIMARY, Keys.KEY_LECTURERS_REGNUMBER_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Lecturers as(String alias) {
        return new Lecturers(alias, this);
    }

    /**
     * Rename this table
     */
    public Lecturers rename(String name) {
        return new Lecturers(name, null);
    }
}
