/**
 * This class is generated by jOOQ
 */
package com.ivo.tables;


import com.ivo.Ivoschool;
import com.ivo.Keys;
import com.ivo.tables.records.ParentsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parents extends TableImpl<ParentsRecord> {

    private static final long serialVersionUID = -389745827;

    /**
     * The reference instance of <code>ivoschool.parents</code>
     */
    public static final Parents PARENTS = new Parents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParentsRecord> getRecordType() {
        return ParentsRecord.class;
    }

    /**
     * The column <code>ivoschool.parents.id</code>.
     */
    public final TableField<ParentsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.name</code>.
     */
    public final TableField<ParentsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.address</code>.
     */
    public final TableField<ParentsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.email</code>.
     */
    public final TableField<ParentsRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.phone_number</code>.
     */
    public final TableField<ParentsRecord, String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.reg_number</code>.
     */
    public final TableField<ParentsRecord, String> REG_NUMBER = createField("reg_number", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.password</code>.
     */
    public final TableField<ParentsRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ivoschool.parents.role</code>.
     */
    public final TableField<ParentsRecord, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("PARENT", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ivoschool.parents.createdAt</code>.
     */
    public final TableField<ParentsRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ivoschool.parents.updatedAt</code>.
     */
    public final TableField<ParentsRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>ivoschool.parents</code> table reference
     */
    public Parents() {
        this("parents", null);
    }

    /**
     * Create an aliased <code>ivoschool.parents</code> table reference
     */
    public Parents(String alias) {
        this(alias, PARENTS);
    }

    private Parents(String alias, Table<ParentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parents(String alias, Table<ParentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ivoschool.IVOSCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParentsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PARENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParentsRecord> getPrimaryKey() {
        return Keys.KEY_PARENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParentsRecord>> getKeys() {
        return Arrays.<UniqueKey<ParentsRecord>>asList(Keys.KEY_PARENTS_PRIMARY, Keys.KEY_PARENTS_EMAIL, Keys.KEY_PARENTS_REGNUMBER_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parents as(String alias) {
        return new Parents(alias, this);
    }

    /**
     * Rename this table
     */
    public Parents rename(String name) {
        return new Parents(name, null);
    }
}
