/**
 * This class is generated by jOOQ
 */
package com.ivo.tables;


import com.ivo.Ivoschool;
import com.ivo.Keys;
import com.ivo.tables.records.StudentsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students extends TableImpl<StudentsRecord> {

    private static final long serialVersionUID = 2023861702;

    /**
     * The reference instance of <code>ivoschool.students</code>
     */
    public static final Students STUDENTS = new Students();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentsRecord> getRecordType() {
        return StudentsRecord.class;
    }

    /**
     * The column <code>ivoschool.students.id</code>.
     */
    public final TableField<StudentsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.reg_number</code>.
     */
    public final TableField<StudentsRecord, String> REG_NUMBER = createField("reg_number", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.class_id</code>.
     */
    public final TableField<StudentsRecord, Integer> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ivoschool.students.first_name</code>.
     */
    public final TableField<StudentsRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.last_name</code>.
     */
    public final TableField<StudentsRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.dob</code>.
     */
    public final TableField<StudentsRecord, String> DOB = createField("dob", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.photo_url</code>.
     */
    public final TableField<StudentsRecord, String> PHOTO_URL = createField("photo_url", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.students.gender</code>.
     */
    public final TableField<StudentsRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(6).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.address</code>.
     */
    public final TableField<StudentsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.nationality</code>.
     */
    public final TableField<StudentsRecord, String> NATIONALITY = createField("nationality", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.language</code>.
     */
    public final TableField<StudentsRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.students.state_of_origin</code>.
     */
    public final TableField<StudentsRecord, String> STATE_OF_ORIGIN = createField("state_of_origin", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.students.phone_number</code>.
     */
    public final TableField<StudentsRecord, String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

    /**
     * The column <code>ivoschool.students.email</code>.
     */
    public final TableField<StudentsRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>ivoschool.students.password</code>.
     */
    public final TableField<StudentsRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>ivoschool.students.role</code>.
     */
    public final TableField<StudentsRecord, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("STUDENT", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ivoschool.students.createdAt</code>.
     */
    public final TableField<StudentsRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ivoschool.students.updatedAt</code>.
     */
    public final TableField<StudentsRecord, Timestamp> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>ivoschool.students.previous_school</code>.
     */
    public final TableField<StudentsRecord, String> PREVIOUS_SCHOOL = createField("previous_school", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>ivoschool.students</code> table reference
     */
    public Students() {
        this("students", null);
    }

    /**
     * Create an aliased <code>ivoschool.students</code> table reference
     */
    public Students(String alias) {
        this(alias, STUDENTS);
    }

    private Students(String alias, Table<StudentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Students(String alias, Table<StudentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ivoschool.IVOSCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StudentsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STUDENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudentsRecord> getPrimaryKey() {
        return Keys.KEY_STUDENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudentsRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentsRecord>>asList(Keys.KEY_STUDENTS_PRIMARY, Keys.KEY_STUDENTS_REGNUMBER_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StudentsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StudentsRecord, ?>>asList(Keys.FK_STUDENTS_CLASSES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Students as(String alias) {
        return new Students(alias, this);
    }

    /**
     * Rename this table
     */
    public Students rename(String name) {
        return new Students(name, null);
    }
}
