/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables.records;


import com.ivo.school.tables.Assignments;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentsRecord extends UpdatableRecordImpl<AssignmentsRecord> implements Record13<Integer, String, String, Integer, String, String, String, Integer, Timestamp, Timestamp, Timestamp, String, BigDecimal> {

    private static final long serialVersionUID = -210183287;

    /**
     * Setter for <code>mydb.assignments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mydb.assignments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.assignments.topic</code>.
     */
    public void setTopic(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mydb.assignments.topic</code>.
     */
    public String getTopic() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mydb.assignments.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mydb.assignments.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mydb.assignments.overall_mark</code>.
     */
    public void setOverallMark(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mydb.assignments.overall_mark</code>.
     */
    public Integer getOverallMark() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mydb.assignments.content_url</code>.
     */
    public void setContentUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mydb.assignments.content_url</code>.
     */
    public String getContentUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mydb.assignments.content_url2</code>.
     */
    public void setContentUrl2(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mydb.assignments.content_url2</code>.
     */
    public String getContentUrl2() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mydb.assignments.content_url3</code>.
     */
    public void setContentUrl3(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mydb.assignments.content_url3</code>.
     */
    public String getContentUrl3() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mydb.assignments.lecturer_id</code>.
     */
    public void setLecturerId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>mydb.assignments.lecturer_id</code>.
     */
    public Integer getLecturerId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>mydb.assignments.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mydb.assignments.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>mydb.assignments.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mydb.assignments.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mydb.assignments.deadline</code>.
     */
    public void setDeadline(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>mydb.assignments.deadline</code>.
     */
    public Timestamp getDeadline() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>mydb.assignments.semester</code>.
     */
    public void setSemester(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mydb.assignments.semester</code>.
     */
    public String getSemester() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mydb.assignments.percentage</code>.
     */
    public void setPercentage(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>mydb.assignments.percentage</code>.
     */
    public BigDecimal getPercentage() {
        return (BigDecimal) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, Integer, String, String, String, Integer, Timestamp, Timestamp, Timestamp, String, BigDecimal> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, Integer, String, String, String, Integer, Timestamp, Timestamp, Timestamp, String, BigDecimal> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Assignments.ASSIGNMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Assignments.ASSIGNMENTS.TOPIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Assignments.ASSIGNMENTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Assignments.ASSIGNMENTS.OVERALL_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Assignments.ASSIGNMENTS.CONTENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Assignments.ASSIGNMENTS.CONTENT_URL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Assignments.ASSIGNMENTS.CONTENT_URL3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Assignments.ASSIGNMENTS.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Assignments.ASSIGNMENTS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Assignments.ASSIGNMENTS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Assignments.ASSIGNMENTS.DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Assignments.ASSIGNMENTS.SEMESTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return Assignments.ASSIGNMENTS.PERCENTAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTopic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOverallMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContentUrl2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getContentUrl3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSemester();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getPercentage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value2(String value) {
        setTopic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value4(Integer value) {
        setOverallMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value5(String value) {
        setContentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value6(String value) {
        setContentUrl2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value7(String value) {
        setContentUrl3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value8(Integer value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value9(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value10(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value11(Timestamp value) {
        setDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value12(String value) {
        setSemester(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord value13(BigDecimal value) {
        setPercentage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Integer value8, Timestamp value9, Timestamp value10, Timestamp value11, String value12, BigDecimal value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentsRecord
     */
    public AssignmentsRecord() {
        super(Assignments.ASSIGNMENTS);
    }

    /**
     * Create a detached, initialised AssignmentsRecord
     */
    public AssignmentsRecord(Integer id, String topic, String content, Integer overallMark, String contentUrl, String contentUrl2, String contentUrl3, Integer lecturerId, Timestamp createdat, Timestamp updatedat, Timestamp deadline, String semester, BigDecimal percentage) {
        super(Assignments.ASSIGNMENTS);

        set(0, id);
        set(1, topic);
        set(2, content);
        set(3, overallMark);
        set(4, contentUrl);
        set(5, contentUrl2);
        set(6, contentUrl3);
        set(7, lecturerId);
        set(8, createdat);
        set(9, updatedat);
        set(10, deadline);
        set(11, semester);
        set(12, percentage);
    }
}
