/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables.records;


import com.ivo.school.tables.ClassNews;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassNewsRecord extends UpdatableRecordImpl<ClassNewsRecord> implements Record5<Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 709391722;

    /**
     * Setter for <code>mydb.class_news.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mydb.class_news.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.class_news.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mydb.class_news.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mydb.class_news.news_id</code>.
     */
    public void setNewsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mydb.class_news.news_id</code>.
     */
    public Integer getNewsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mydb.class_news.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>mydb.class_news.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>mydb.class_news.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mydb.class_news.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ClassNews.CLASS_NEWS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ClassNews.CLASS_NEWS.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ClassNews.CLASS_NEWS.NEWS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ClassNews.CLASS_NEWS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ClassNews.CLASS_NEWS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord value2(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord value3(Integer value) {
        setNewsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord value5(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassNewsRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassNewsRecord
     */
    public ClassNewsRecord() {
        super(ClassNews.CLASS_NEWS);
    }

    /**
     * Create a detached, initialised ClassNewsRecord
     */
    public ClassNewsRecord(Integer id, Integer classId, Integer newsId, Timestamp createdat, Timestamp updatedat) {
        super(ClassNews.CLASS_NEWS);

        set(0, id);
        set(1, classId);
        set(2, newsId);
        set(3, createdat);
        set(4, updatedat);
    }
}
