/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables.records;


import com.ivo.school.tables.PeriodNotes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeriodNotesRecord extends UpdatableRecordImpl<PeriodNotesRecord> implements Record5<Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -254347657;

    /**
     * Setter for <code>mydb.period_notes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mydb.period_notes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.period_notes.note_id</code>.
     */
    public void setNoteId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mydb.period_notes.note_id</code>.
     */
    public Integer getNoteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mydb.period_notes.period_id</code>.
     */
    public void setPeriodId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mydb.period_notes.period_id</code>.
     */
    public Integer getPeriodId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mydb.period_notes.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>mydb.period_notes.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>mydb.period_notes.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mydb.period_notes.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PeriodNotes.PERIOD_NOTES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PeriodNotes.PERIOD_NOTES.NOTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PeriodNotes.PERIOD_NOTES.PERIOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return PeriodNotes.PERIOD_NOTES.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PeriodNotes.PERIOD_NOTES.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNoteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPeriodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord value2(Integer value) {
        setNoteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord value3(Integer value) {
        setPeriodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord value5(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeriodNotesRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PeriodNotesRecord
     */
    public PeriodNotesRecord() {
        super(PeriodNotes.PERIOD_NOTES);
    }

    /**
     * Create a detached, initialised PeriodNotesRecord
     */
    public PeriodNotesRecord(Integer id, Integer noteId, Integer periodId, Timestamp createdat, Timestamp updatedat) {
        super(PeriodNotes.PERIOD_NOTES);

        set(0, id);
        set(1, noteId);
        set(2, periodId);
        set(3, createdat);
        set(4, updatedat);
    }
}
