/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables.records;


import com.ivo.school.tables.StudentsCoursesAssignments;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsCoursesAssignmentsRecord extends UpdatableRecordImpl<StudentsCoursesAssignmentsRecord> implements Record8<Integer, Integer, Integer, Integer, BigDecimal, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -191248442;

    /**
     * Setter for <code>mydb.students_courses_assignments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.assignment_id</code>.
     */
    public void setAssignmentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.assignment_id</code>.
     */
    public Integer getAssignmentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.score</code>.
     */
    public void setScore(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.score</code>.
     */
    public BigDecimal getScore() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.assignment_url</code>.
     */
    public void setAssignmentUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.assignment_url</code>.
     */
    public String getAssignmentUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mydb.students_courses_assignments.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mydb.students_courses_assignments.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ASSIGNMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.ASSIGNMENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAssignmentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value2(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value3(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value4(Integer value) {
        setAssignmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value5(BigDecimal value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value6(String value) {
        setAssignmentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value7(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord value8(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsCoursesAssignmentsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, BigDecimal value5, String value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsCoursesAssignmentsRecord
     */
    public StudentsCoursesAssignmentsRecord() {
        super(StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS);
    }

    /**
     * Create a detached, initialised StudentsCoursesAssignmentsRecord
     */
    public StudentsCoursesAssignmentsRecord(Integer id, Integer studentId, Integer courseId, Integer assignmentId, BigDecimal score, String assignmentUrl, Timestamp createdat, Timestamp updatedat) {
        super(StudentsCoursesAssignments.STUDENTS_COURSES_ASSIGNMENTS);

        set(0, id);
        set(1, studentId);
        set(2, courseId);
        set(3, assignmentId);
        set(4, score);
        set(5, assignmentUrl);
        set(6, createdat);
        set(7, updatedat);
    }
}
