/**
 * This class is generated by jOOQ
 */
package com.ivo.school.tables.records;


import com.ivo.school.tables.Students;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsRecord extends UpdatableRecordImpl<StudentsRecord> implements Record19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -2078358929;

    /**
     * Setter for <code>mydb.students.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mydb.students.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.students.reg_number</code>.
     */
    public void setRegNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mydb.students.reg_number</code>.
     */
    public String getRegNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mydb.students.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mydb.students.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mydb.students.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mydb.students.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mydb.students.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mydb.students.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mydb.students.dob</code>.
     */
    public void setDob(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mydb.students.dob</code>.
     */
    public String getDob() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mydb.students.photo_url</code>.
     */
    public void setPhotoUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mydb.students.photo_url</code>.
     */
    public String getPhotoUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mydb.students.gender</code>.
     */
    public void setGender(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mydb.students.gender</code>.
     */
    public String getGender() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mydb.students.address</code>.
     */
    public void setAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mydb.students.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mydb.students.nationality</code>.
     */
    public void setNationality(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mydb.students.nationality</code>.
     */
    public String getNationality() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mydb.students.language</code>.
     */
    public void setLanguage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mydb.students.language</code>.
     */
    public String getLanguage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mydb.students.state_of_origin</code>.
     */
    public void setStateOfOrigin(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mydb.students.state_of_origin</code>.
     */
    public String getStateOfOrigin() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mydb.students.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mydb.students.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mydb.students.email</code>.
     */
    public void setEmail(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mydb.students.email</code>.
     */
    public String getEmail() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mydb.students.password</code>.
     */
    public void setPassword(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mydb.students.password</code>.
     */
    public String getPassword() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mydb.students.role</code>.
     */
    public void setRole(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mydb.students.role</code>.
     */
    public String getRole() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mydb.students.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>mydb.students.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>mydb.students.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>mydb.students.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>mydb.students.previous_school</code>.
     */
    public void setPreviousSchool(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mydb.students.previous_school</code>.
     */
    public String getPreviousSchool() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Students.STUDENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Students.STUDENTS.REG_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Students.STUDENTS.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Students.STUDENTS.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Students.STUDENTS.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Students.STUDENTS.DOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Students.STUDENTS.PHOTO_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Students.STUDENTS.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Students.STUDENTS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Students.STUDENTS.NATIONALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Students.STUDENTS.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Students.STUDENTS.STATE_OF_ORIGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Students.STUDENTS.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Students.STUDENTS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Students.STUDENTS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Students.STUDENTS.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Students.STUDENTS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Students.STUDENTS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Students.STUDENTS.PREVIOUS_SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRegNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNationality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getStateOfOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getPreviousSchool();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value2(String value) {
        setRegNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value3(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value5(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value6(String value) {
        setDob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value7(String value) {
        setPhotoUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value8(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value9(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value10(String value) {
        setNationality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value11(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value12(String value) {
        setStateOfOrigin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value13(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value14(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value15(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value16(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value17(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value18(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value19(String value) {
        setPreviousSchool(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, Timestamp value17, Timestamp value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsRecord
     */
    public StudentsRecord() {
        super(Students.STUDENTS);
    }

    /**
     * Create a detached, initialised StudentsRecord
     */
    public StudentsRecord(Integer id, String regNumber, Integer classId, String firstName, String lastName, String dob, String photoUrl, String gender, String address, String nationality, String language, String stateOfOrigin, String phoneNumber, String email, String password, String role, Timestamp createdat, Timestamp updatedat, String previousSchool) {
        super(Students.STUDENTS);

        set(0, id);
        set(1, regNumber);
        set(2, classId);
        set(3, firstName);
        set(4, lastName);
        set(5, dob);
        set(6, photoUrl);
        set(7, gender);
        set(8, address);
        set(9, nationality);
        set(10, language);
        set(11, stateOfOrigin);
        set(12, phoneNumber);
        set(13, email);
        set(14, password);
        set(15, role);
        set(16, createdat);
        set(17, updatedat);
        set(18, previousSchool);
    }
}
