/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.Attendances;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendancesRecord extends UpdatableRecordImpl<AttendancesRecord> implements Record5<Integer, Integer, Integer, Date, Date> {

    private static final long serialVersionUID = -217788523;

    /**
     * Setter for <code>ivoschool.attendances.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.attendances.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.attendances.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.attendances.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ivoschool.attendances.period_id</code>.
     */
    public void setPeriodId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.attendances.period_id</code>.
     */
    public Integer getPeriodId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ivoschool.attendances.createdAt</code>.
     */
    public void setCreatedat(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.attendances.createdAt</code>.
     */
    public Date getCreatedat() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>ivoschool.attendances.updatedAt</code>.
     */
    public void setUpdatedat(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.attendances.updatedAt</code>.
     */
    public Date getUpdatedat() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Date, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Date, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Attendances.ATTENDANCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Attendances.ATTENDANCES.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Attendances.ATTENDANCES.PERIOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Attendances.ATTENDANCES.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Attendances.ATTENDANCES.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPeriodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord value2(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord value3(Integer value) {
        setPeriodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord value4(Date value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord value5(Date value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AttendancesRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttendancesRecord
     */
    public AttendancesRecord() {
        super(Attendances.ATTENDANCES);
    }

    /**
     * Create a detached, initialised AttendancesRecord
     */
    public AttendancesRecord(Integer id, Integer studentId, Integer periodId, Date createdat, Date updatedat) {
        super(Attendances.ATTENDANCES);

        set(0, id);
        set(1, studentId);
        set(2, periodId);
        set(3, createdat);
        set(4, updatedat);
    }
}
