/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.Classes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassesRecord extends UpdatableRecordImpl<ClassesRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, Integer, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = -1479681922;

    /**
     * Setter for <code>ivoschool.classes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.classes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.classes.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.classes.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ivoschool.classes.about</code>.
     */
    public void setAbout(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.classes.about</code>.
     */
    public String getAbout() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ivoschool.classes.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.classes.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ivoschool.classes.colour</code>.
     */
    public void setColour(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.classes.colour</code>.
     */
    public String getColour() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ivoschool.classes.short_name</code>.
     */
    public void setShortName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ivoschool.classes.short_name</code>.
     */
    public String getShortName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ivoschool.classes.photo_url</code>.
     */
    public void setPhotoUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ivoschool.classes.photo_url</code>.
     */
    public String getPhotoUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ivoschool.classes.photo_url2</code>.
     */
    public void setPhotoUrl2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ivoschool.classes.photo_url2</code>.
     */
    public String getPhotoUrl2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ivoschool.classes.photo_url3</code>.
     */
    public void setPhotoUrl3(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ivoschool.classes.photo_url3</code>.
     */
    public String getPhotoUrl3() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ivoschool.classes.lecturer_id</code>.
     */
    public void setLecturerId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>ivoschool.classes.lecturer_id</code>.
     */
    public Integer getLecturerId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>ivoschool.classes.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>ivoschool.classes.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>ivoschool.classes.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>ivoschool.classes.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>ivoschool.classes.level</code>.
     */
    public void setLevel(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>ivoschool.classes.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, Integer, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, Integer, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Classes.CLASSES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Classes.CLASSES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Classes.CLASSES.ABOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Classes.CLASSES.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Classes.CLASSES.COLOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Classes.CLASSES.SHORT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Classes.CLASSES.PHOTO_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Classes.CLASSES.PHOTO_URL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Classes.CLASSES.PHOTO_URL3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Classes.CLASSES.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Classes.CLASSES.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Classes.CLASSES.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Classes.CLASSES.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAbout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getColour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getShortName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhotoUrl2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPhotoUrl3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value3(String value) {
        setAbout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value5(String value) {
        setColour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value6(String value) {
        setShortName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value7(String value) {
        setPhotoUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value8(String value) {
        setPhotoUrl2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value9(String value) {
        setPhotoUrl3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value10(Integer value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value11(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value12(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord value13(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Integer value10, Timestamp value11, Timestamp value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassesRecord
     */
    public ClassesRecord() {
        super(Classes.CLASSES);
    }

    /**
     * Create a detached, initialised ClassesRecord
     */
    public ClassesRecord(Integer id, String name, String about, String location, String colour, String shortName, String photoUrl, String photoUrl2, String photoUrl3, Integer lecturerId, Timestamp createdat, Timestamp updatedat, Integer level) {
        super(Classes.CLASSES);

        set(0, id);
        set(1, name);
        set(2, about);
        set(3, location);
        set(4, colour);
        set(5, shortName);
        set(6, photoUrl);
        set(7, photoUrl2);
        set(8, photoUrl3);
        set(9, lecturerId);
        set(10, createdat);
        set(11, updatedat);
        set(12, level);
    }
}
