/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.CourseNews;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseNewsRecord extends UpdatableRecordImpl<CourseNewsRecord> implements Record5<Integer, Integer, Integer, Date, Date> {

    private static final long serialVersionUID = 1779782760;

    /**
     * Setter for <code>ivoschool.course_news.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.course_news.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.course_news.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.course_news.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ivoschool.course_news.news_id</code>.
     */
    public void setNewsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.course_news.news_id</code>.
     */
    public Integer getNewsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ivoschool.course_news.createdAt</code>.
     */
    public void setCreatedat(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.course_news.createdAt</code>.
     */
    public Date getCreatedat() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>ivoschool.course_news.updatedAt</code>.
     */
    public void setUpdatedat(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.course_news.updatedAt</code>.
     */
    public Date getUpdatedat() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Date, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Date, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CourseNews.COURSE_NEWS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CourseNews.COURSE_NEWS.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CourseNews.COURSE_NEWS.NEWS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return CourseNews.COURSE_NEWS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return CourseNews.COURSE_NEWS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord value2(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord value3(Integer value) {
        setNewsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord value4(Date value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord value5(Date value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseNewsRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseNewsRecord
     */
    public CourseNewsRecord() {
        super(CourseNews.COURSE_NEWS);
    }

    /**
     * Create a detached, initialised CourseNewsRecord
     */
    public CourseNewsRecord(Integer id, Integer courseId, Integer newsId, Date createdat, Date updatedat) {
        super(CourseNews.COURSE_NEWS);

        set(0, id);
        set(1, courseId);
        set(2, newsId);
        set(3, createdat);
        set(4, updatedat);
    }
}
