/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.Exams;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamsRecord extends UpdatableRecordImpl<ExamsRecord> implements Record12<Integer, String, String, String, String, Integer, Timestamp, Timestamp, Integer, String, String, BigDecimal> {

    private static final long serialVersionUID = -2019186310;

    /**
     * Setter for <code>ivoschool.exams.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.exams.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.exams.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.exams.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ivoschool.exams.content_url</code>.
     */
    public void setContentUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.exams.content_url</code>.
     */
    public String getContentUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ivoschool.exams.content_url2</code>.
     */
    public void setContentUrl2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.exams.content_url2</code>.
     */
    public String getContentUrl2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ivoschool.exams.content_url3</code>.
     */
    public void setContentUrl3(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.exams.content_url3</code>.
     */
    public String getContentUrl3() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ivoschool.exams.lecturer_id</code>.
     */
    public void setLecturerId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ivoschool.exams.lecturer_id</code>.
     */
    public Integer getLecturerId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ivoschool.exams.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>ivoschool.exams.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ivoschool.exams.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ivoschool.exams.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ivoschool.exams.overall_mark</code>.
     */
    public void setOverallMark(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>ivoschool.exams.overall_mark</code>.
     */
    public Integer getOverallMark() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>ivoschool.exams.topic</code>.
     */
    public void setTopic(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ivoschool.exams.topic</code>.
     */
    public String getTopic() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ivoschool.exams.semester</code>.
     */
    public void setSemester(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ivoschool.exams.semester</code>.
     */
    public String getSemester() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ivoschool.exams.percentage</code>.
     */
    public void setPercentage(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>ivoschool.exams.percentage</code>.
     */
    public BigDecimal getPercentage() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Integer, Timestamp, Timestamp, Integer, String, String, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Integer, Timestamp, Timestamp, Integer, String, String, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Exams.EXAMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Exams.EXAMS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Exams.EXAMS.CONTENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Exams.EXAMS.CONTENT_URL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Exams.EXAMS.CONTENT_URL3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Exams.EXAMS.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Exams.EXAMS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Exams.EXAMS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Exams.EXAMS.OVERALL_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Exams.EXAMS.TOPIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Exams.EXAMS.SEMESTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return Exams.EXAMS.PERCENTAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContentUrl2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContentUrl3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getOverallMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTopic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getSemester();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getPercentage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value3(String value) {
        setContentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value4(String value) {
        setContentUrl2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value5(String value) {
        setContentUrl3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value6(Integer value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value7(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value8(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value9(Integer value) {
        setOverallMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value10(String value) {
        setTopic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value11(String value) {
        setSemester(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord value12(BigDecimal value) {
        setPercentage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamsRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Timestamp value7, Timestamp value8, Integer value9, String value10, String value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExamsRecord
     */
    public ExamsRecord() {
        super(Exams.EXAMS);
    }

    /**
     * Create a detached, initialised ExamsRecord
     */
    public ExamsRecord(Integer id, String content, String contentUrl, String contentUrl2, String contentUrl3, Integer lecturerId, Timestamp createdat, Timestamp updatedat, Integer overallMark, String topic, String semester, BigDecimal percentage) {
        super(Exams.EXAMS);

        set(0, id);
        set(1, content);
        set(2, contentUrl);
        set(3, contentUrl2);
        set(4, contentUrl3);
        set(5, lecturerId);
        set(6, createdat);
        set(7, updatedat);
        set(8, overallMark);
        set(9, topic);
        set(10, semester);
        set(11, percentage);
    }
}
