/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.Lecturers;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturersRecord extends UpdatableRecordImpl<LecturersRecord> implements Record19<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 866833151;

    /**
     * Setter for <code>ivoschool.lecturers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.lecturers.reg_number</code>.
     */
    public void setRegNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.reg_number</code>.
     */
    public String getRegNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ivoschool.lecturers.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ivoschool.lecturers.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ivoschool.lecturers.dob</code>.
     */
    public void setDob(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.dob</code>.
     */
    public String getDob() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ivoschool.lecturers.qualification</code>.
     */
    public void setQualification(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.qualification</code>.
     */
    public String getQualification() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ivoschool.lecturers.photo_url</code>.
     */
    public void setPhotoUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.photo_url</code>.
     */
    public String getPhotoUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ivoschool.lecturers.gender</code>.
     */
    public void setGender(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.gender</code>.
     */
    public String getGender() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ivoschool.lecturers.address</code>.
     */
    public void setAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ivoschool.lecturers.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ivoschool.lecturers.email</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ivoschool.lecturers.nationality</code>.
     */
    public void setNationality(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.nationality</code>.
     */
    public String getNationality() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ivoschool.lecturers.language</code>.
     */
    public void setLanguage(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.language</code>.
     */
    public String getLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ivoschool.lecturers.state_of_origin</code>.
     */
    public void setStateOfOrigin(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.state_of_origin</code>.
     */
    public String getStateOfOrigin() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ivoschool.lecturers.password</code>.
     */
    public void setPassword(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.password</code>.
     */
    public String getPassword() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ivoschool.lecturers.role</code>.
     */
    public void setRole(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.role</code>.
     */
    public String getRole() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ivoschool.lecturers.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>ivoschool.lecturers.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>ivoschool.lecturers.previous_work_place</code>.
     */
    public void setPreviousWorkPlace(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers.previous_work_place</code>.
     */
    public String getPreviousWorkPlace() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Lecturers.LECTURERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Lecturers.LECTURERS.REG_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Lecturers.LECTURERS.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Lecturers.LECTURERS.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Lecturers.LECTURERS.DOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Lecturers.LECTURERS.QUALIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Lecturers.LECTURERS.PHOTO_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Lecturers.LECTURERS.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Lecturers.LECTURERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Lecturers.LECTURERS.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Lecturers.LECTURERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Lecturers.LECTURERS.NATIONALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Lecturers.LECTURERS.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Lecturers.LECTURERS.STATE_OF_ORIGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Lecturers.LECTURERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Lecturers.LECTURERS.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Lecturers.LECTURERS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Lecturers.LECTURERS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Lecturers.LECTURERS.PREVIOUS_WORK_PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRegNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getQualification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getNationality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getStateOfOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getPreviousWorkPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value2(String value) {
        setRegNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value4(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value5(String value) {
        setDob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value6(String value) {
        setQualification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value7(String value) {
        setPhotoUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value8(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value9(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value10(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value11(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value12(String value) {
        setNationality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value13(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value14(String value) {
        setStateOfOrigin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value15(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value16(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value17(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value18(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value19(String value) {
        setPreviousWorkPlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, Timestamp value17, Timestamp value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturersRecord
     */
    public LecturersRecord() {
        super(Lecturers.LECTURERS);
    }

    /**
     * Create a detached, initialised LecturersRecord
     */
    public LecturersRecord(Integer id, String regNumber, String firstName, String lastName, String dob, String qualification, String photoUrl, String gender, String address, String phoneNumber, String email, String nationality, String language, String stateOfOrigin, String password, String role, Timestamp createdat, Timestamp updatedat, String previousWorkPlace) {
        super(Lecturers.LECTURERS);

        set(0, id);
        set(1, regNumber);
        set(2, firstName);
        set(3, lastName);
        set(4, dob);
        set(5, qualification);
        set(6, photoUrl);
        set(7, gender);
        set(8, address);
        set(9, phoneNumber);
        set(10, email);
        set(11, nationality);
        set(12, language);
        set(13, stateOfOrigin);
        set(14, password);
        set(15, role);
        set(16, createdat);
        set(17, updatedat);
        set(18, previousWorkPlace);
    }
}
