/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.LecturersCourses;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturersCoursesRecord extends UpdatableRecordImpl<LecturersCoursesRecord> implements Record5<Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1535044499;

    /**
     * Setter for <code>ivoschool.lecturers_courses.lecturer_id</code>.
     */
    public void setLecturerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers_courses.lecturer_id</code>.
     */
    public Integer getLecturerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.lecturers_courses.course_id</code>.
     */
    public void setCourseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers_courses.course_id</code>.
     */
    public Integer getCourseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ivoschool.lecturers_courses.aims</code>.
     */
    public void setAims(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers_courses.aims</code>.
     */
    public String getAims() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ivoschool.lecturers_courses.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers_courses.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>ivoschool.lecturers_courses.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.lecturers_courses.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LecturersCourses.LECTURERS_COURSES.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return LecturersCourses.LECTURERS_COURSES.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LecturersCourses.LECTURERS_COURSES.AIMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return LecturersCourses.LECTURERS_COURSES.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return LecturersCourses.LECTURERS_COURSES.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAims();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord value1(Integer value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord value2(Integer value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord value3(String value) {
        setAims(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord value5(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersCoursesRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturersCoursesRecord
     */
    public LecturersCoursesRecord() {
        super(LecturersCourses.LECTURERS_COURSES);
    }

    /**
     * Create a detached, initialised LecturersCoursesRecord
     */
    public LecturersCoursesRecord(Integer lecturerId, Integer courseId, String aims, Timestamp createdat, Timestamp updatedat) {
        super(LecturersCourses.LECTURERS_COURSES);

        set(0, lecturerId);
        set(1, courseId);
        set(2, aims);
        set(3, createdat);
        set(4, updatedat);
    }
}
