/**
 * This class is generated by jOOQ
 */
package com.ivo.tables.records;


import com.ivo.tables.News;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsRecord extends UpdatableRecordImpl<NewsRecord> implements Record9<Integer, String, String, String, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 513426501;

    /**
     * Setter for <code>ivoschool.news.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ivoschool.news.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ivoschool.news.topic</code>.
     */
    public void setTopic(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ivoschool.news.topic</code>.
     */
    public String getTopic() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ivoschool.news.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ivoschool.news.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ivoschool.news.content_url</code>.
     */
    public void setContentUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ivoschool.news.content_url</code>.
     */
    public String getContentUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ivoschool.news.content_url2</code>.
     */
    public void setContentUrl2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ivoschool.news.content_url2</code>.
     */
    public String getContentUrl2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ivoschool.news.content_url3</code>.
     */
    public void setContentUrl3(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ivoschool.news.content_url3</code>.
     */
    public String getContentUrl3() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ivoschool.news.lecturer_id</code>.
     */
    public void setLecturerId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ivoschool.news.lecturer_id</code>.
     */
    public Integer getLecturerId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ivoschool.news.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ivoschool.news.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ivoschool.news.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>ivoschool.news.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return News.NEWS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return News.NEWS.TOPIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return News.NEWS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return News.NEWS.CONTENT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return News.NEWS.CONTENT_URL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return News.NEWS.CONTENT_URL3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return News.NEWS.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return News.NEWS.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return News.NEWS.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTopic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContentUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContentUrl2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContentUrl3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value2(String value) {
        setTopic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value4(String value) {
        setContentUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value5(String value) {
        setContentUrl2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value6(String value) {
        setContentUrl3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value7(Integer value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value8(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord value9(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NewsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsRecord
     */
    public NewsRecord() {
        super(News.NEWS);
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(Integer id, String topic, String content, String contentUrl, String contentUrl2, String contentUrl3, Integer lecturerId, Timestamp createdat, Timestamp updatedat) {
        super(News.NEWS);

        set(0, id);
        set(1, topic);
        set(2, content);
        set(3, contentUrl);
        set(4, contentUrl2);
        set(5, contentUrl3);
        set(6, lecturerId);
        set(7, createdat);
        set(8, updatedat);
    }
}
